package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Container;
import com.megalink.study.model.nochange.ContainerExample;
import com.megalink.study.model.nochange.ContainerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGContainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int countByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int deleteByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long container_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int insert(ContainerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int insertSelective(ContainerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    List<ContainerWithBLOBs> selectByExampleWithBLOBs(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    List<Container> selectByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    ContainerWithBLOBs selectByPrimaryKey(Long container_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ContainerWithBLOBs record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ContainerWithBLOBs record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContainerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ContainerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Container record);
}