package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Domain;
import com.megalink.study.model.nochange.DomainExample;
import com.megalink.study.model.nochange.DomainWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int countByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int deleteByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long DOMAIN_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int insert(DomainWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int insertSelective(DomainWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    List<DomainWithBLOBs> selectByExampleWithBLOBs(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    List<Domain> selectByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    DomainWithBLOBs selectByPrimaryKey(Long DOMAIN_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DomainWithBLOBs record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") DomainWithBLOBs record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DomainWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DomainWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Domain record);
}