package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Folder;
import com.megalink.study.model.nochange.FolderExample;
import com.megalink.study.model.nochange.FolderWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int countByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int deleteByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long FOLDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int insert(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int insertSelective(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    List<FolderWithBLOBs> selectByExampleWithBLOBs(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    List<Folder> selectByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    FolderWithBLOBs selectByPrimaryKey(Long FOLDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FolderWithBLOBs record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FolderWithBLOBs record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Folder record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Folder record);
}