package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Hansenn;
import com.megalink.study.model.nochange.HansennExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGHansennMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int countByExample(HansennExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int deleteByExample(HansennExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int insert(Hansenn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int insertSelective(Hansenn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    List<Hansenn> selectByExample(HansennExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hansenn record, @Param("example") HansennExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen03
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hansenn record, @Param("example") HansennExample example);
}