package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Lcmuser;
import com.megalink.study.model.nochange.LcmuserExample;
import com.megalink.study.model.nochange.LcmuserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGLcmuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int countByExample(LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int deleteByExample(LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int insert(LcmuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int insertSelective(LcmuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    List<LcmuserWithBLOBs> selectByExampleWithBLOBs(LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    List<Lcmuser> selectByExample(LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    LcmuserWithBLOBs selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LcmuserWithBLOBs record, @Param("example") LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") LcmuserWithBLOBs record, @Param("example") LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Lcmuser record, @Param("example") LcmuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LcmuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(LcmuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcmuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lcmuser record);
}