package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Wfdefine;
import com.megalink.study.model.nochange.WfdefineExample;
import com.megalink.study.model.nochange.WfdefineWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGWfdefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int countByExample(WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int deleteByExample(WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int insert(WfdefineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int insertSelective(WfdefineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    List<WfdefineWithBLOBs> selectByExampleWithBLOBs(WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    List<Wfdefine> selectByExample(WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    WfdefineWithBLOBs selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WfdefineWithBLOBs record, @Param("example") WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WfdefineWithBLOBs record, @Param("example") WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Wfdefine record, @Param("example") WfdefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WfdefineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WfdefineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wfdefine record);
}