package com.megalink.study.model.nochange;

import java.math.BigDecimal;
import java.util.Date;

public class Container {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.container_id
     *
     * @mbggenerated
     */
    private Long container_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.creatorid
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.domain_id
     *
     * @mbggenerated
     */
    private Long domain_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.isavailable
     *
     * @mbggenerated
     */
    private BigDecimal isavailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int1
     *
     * @mbggenerated
     */
    private Integer int1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int2
     *
     * @mbggenerated
     */
    private Integer int2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int3
     *
     * @mbggenerated
     */
    private Integer int3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int4
     *
     * @mbggenerated
     */
    private Integer int4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int5
     *
     * @mbggenerated
     */
    private Integer int5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int6
     *
     * @mbggenerated
     */
    private Integer int6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int7
     *
     * @mbggenerated
     */
    private Integer int7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int8
     *
     * @mbggenerated
     */
    private Integer int8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int9
     *
     * @mbggenerated
     */
    private Integer int9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.int10
     *
     * @mbggenerated
     */
    private Integer int10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date1
     *
     * @mbggenerated
     */
    private Date date1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date2
     *
     * @mbggenerated
     */
    private Date date2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date3
     *
     * @mbggenerated
     */
    private Date date3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date4
     *
     * @mbggenerated
     */
    private Date date4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date5
     *
     * @mbggenerated
     */
    private Date date5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date6
     *
     * @mbggenerated
     */
    private Date date6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date7
     *
     * @mbggenerated
     */
    private Date date7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date8
     *
     * @mbggenerated
     */
    private Date date8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date9
     *
     * @mbggenerated
     */
    private Date date9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.date10
     *
     * @mbggenerated
     */
    private Date date10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float1
     *
     * @mbggenerated
     */
    private Float float1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float2
     *
     * @mbggenerated
     */
    private Float float2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float3
     *
     * @mbggenerated
     */
    private Float float3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float4
     *
     * @mbggenerated
     */
    private Float float4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float5
     *
     * @mbggenerated
     */
    private Float float5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float6
     *
     * @mbggenerated
     */
    private Float float6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float7
     *
     * @mbggenerated
     */
    private Float float7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float8
     *
     * @mbggenerated
     */
    private Float float8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float9
     *
     * @mbggenerated
     */
    private Float float9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.float10
     *
     * @mbggenerated
     */
    private Float float10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.container_id
     *
     * @return the value of container.container_id
     *
     * @mbggenerated
     */
    public Long getContainer_id() {
        return container_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.container_id
     *
     * @param container_id the value for container.container_id
     *
     * @mbggenerated
     */
    public void setContainer_id(Long container_id) {
        this.container_id = container_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.created
     *
     * @return the value of container.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.created
     *
     * @param created the value for container.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.modified
     *
     * @return the value of container.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.modified
     *
     * @param modified the value for container.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.creatorid
     *
     * @return the value of container.creatorid
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.creatorid
     *
     * @param creatorid the value for container.creatorid
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.name
     *
     * @return the value of container.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.name
     *
     * @param name the value for container.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.description
     *
     * @return the value of container.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.description
     *
     * @param description the value for container.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.domain_id
     *
     * @return the value of container.domain_id
     *
     * @mbggenerated
     */
    public Long getDomain_id() {
        return domain_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.domain_id
     *
     * @param domain_id the value for container.domain_id
     *
     * @mbggenerated
     */
    public void setDomain_id(Long domain_id) {
        this.domain_id = domain_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.isavailable
     *
     * @return the value of container.isavailable
     *
     * @mbggenerated
     */
    public BigDecimal getIsavailable() {
        return isavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.isavailable
     *
     * @param isavailable the value for container.isavailable
     *
     * @mbggenerated
     */
    public void setIsavailable(BigDecimal isavailable) {
        this.isavailable = isavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int1
     *
     * @return the value of container.int1
     *
     * @mbggenerated
     */
    public Integer getInt1() {
        return int1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int1
     *
     * @param int1 the value for container.int1
     *
     * @mbggenerated
     */
    public void setInt1(Integer int1) {
        this.int1 = int1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int2
     *
     * @return the value of container.int2
     *
     * @mbggenerated
     */
    public Integer getInt2() {
        return int2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int2
     *
     * @param int2 the value for container.int2
     *
     * @mbggenerated
     */
    public void setInt2(Integer int2) {
        this.int2 = int2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int3
     *
     * @return the value of container.int3
     *
     * @mbggenerated
     */
    public Integer getInt3() {
        return int3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int3
     *
     * @param int3 the value for container.int3
     *
     * @mbggenerated
     */
    public void setInt3(Integer int3) {
        this.int3 = int3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int4
     *
     * @return the value of container.int4
     *
     * @mbggenerated
     */
    public Integer getInt4() {
        return int4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int4
     *
     * @param int4 the value for container.int4
     *
     * @mbggenerated
     */
    public void setInt4(Integer int4) {
        this.int4 = int4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int5
     *
     * @return the value of container.int5
     *
     * @mbggenerated
     */
    public Integer getInt5() {
        return int5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int5
     *
     * @param int5 the value for container.int5
     *
     * @mbggenerated
     */
    public void setInt5(Integer int5) {
        this.int5 = int5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int6
     *
     * @return the value of container.int6
     *
     * @mbggenerated
     */
    public Integer getInt6() {
        return int6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int6
     *
     * @param int6 the value for container.int6
     *
     * @mbggenerated
     */
    public void setInt6(Integer int6) {
        this.int6 = int6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int7
     *
     * @return the value of container.int7
     *
     * @mbggenerated
     */
    public Integer getInt7() {
        return int7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int7
     *
     * @param int7 the value for container.int7
     *
     * @mbggenerated
     */
    public void setInt7(Integer int7) {
        this.int7 = int7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int8
     *
     * @return the value of container.int8
     *
     * @mbggenerated
     */
    public Integer getInt8() {
        return int8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int8
     *
     * @param int8 the value for container.int8
     *
     * @mbggenerated
     */
    public void setInt8(Integer int8) {
        this.int8 = int8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int9
     *
     * @return the value of container.int9
     *
     * @mbggenerated
     */
    public Integer getInt9() {
        return int9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int9
     *
     * @param int9 the value for container.int9
     *
     * @mbggenerated
     */
    public void setInt9(Integer int9) {
        this.int9 = int9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.int10
     *
     * @return the value of container.int10
     *
     * @mbggenerated
     */
    public Integer getInt10() {
        return int10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.int10
     *
     * @param int10 the value for container.int10
     *
     * @mbggenerated
     */
    public void setInt10(Integer int10) {
        this.int10 = int10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date1
     *
     * @return the value of container.date1
     *
     * @mbggenerated
     */
    public Date getDate1() {
        return date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date1
     *
     * @param date1 the value for container.date1
     *
     * @mbggenerated
     */
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date2
     *
     * @return the value of container.date2
     *
     * @mbggenerated
     */
    public Date getDate2() {
        return date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date2
     *
     * @param date2 the value for container.date2
     *
     * @mbggenerated
     */
    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date3
     *
     * @return the value of container.date3
     *
     * @mbggenerated
     */
    public Date getDate3() {
        return date3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date3
     *
     * @param date3 the value for container.date3
     *
     * @mbggenerated
     */
    public void setDate3(Date date3) {
        this.date3 = date3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date4
     *
     * @return the value of container.date4
     *
     * @mbggenerated
     */
    public Date getDate4() {
        return date4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date4
     *
     * @param date4 the value for container.date4
     *
     * @mbggenerated
     */
    public void setDate4(Date date4) {
        this.date4 = date4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date5
     *
     * @return the value of container.date5
     *
     * @mbggenerated
     */
    public Date getDate5() {
        return date5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date5
     *
     * @param date5 the value for container.date5
     *
     * @mbggenerated
     */
    public void setDate5(Date date5) {
        this.date5 = date5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date6
     *
     * @return the value of container.date6
     *
     * @mbggenerated
     */
    public Date getDate6() {
        return date6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date6
     *
     * @param date6 the value for container.date6
     *
     * @mbggenerated
     */
    public void setDate6(Date date6) {
        this.date6 = date6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date7
     *
     * @return the value of container.date7
     *
     * @mbggenerated
     */
    public Date getDate7() {
        return date7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date7
     *
     * @param date7 the value for container.date7
     *
     * @mbggenerated
     */
    public void setDate7(Date date7) {
        this.date7 = date7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date8
     *
     * @return the value of container.date8
     *
     * @mbggenerated
     */
    public Date getDate8() {
        return date8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date8
     *
     * @param date8 the value for container.date8
     *
     * @mbggenerated
     */
    public void setDate8(Date date8) {
        this.date8 = date8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date9
     *
     * @return the value of container.date9
     *
     * @mbggenerated
     */
    public Date getDate9() {
        return date9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date9
     *
     * @param date9 the value for container.date9
     *
     * @mbggenerated
     */
    public void setDate9(Date date9) {
        this.date9 = date9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.date10
     *
     * @return the value of container.date10
     *
     * @mbggenerated
     */
    public Date getDate10() {
        return date10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.date10
     *
     * @param date10 the value for container.date10
     *
     * @mbggenerated
     */
    public void setDate10(Date date10) {
        this.date10 = date10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float1
     *
     * @return the value of container.float1
     *
     * @mbggenerated
     */
    public Float getFloat1() {
        return float1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float1
     *
     * @param float1 the value for container.float1
     *
     * @mbggenerated
     */
    public void setFloat1(Float float1) {
        this.float1 = float1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float2
     *
     * @return the value of container.float2
     *
     * @mbggenerated
     */
    public Float getFloat2() {
        return float2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float2
     *
     * @param float2 the value for container.float2
     *
     * @mbggenerated
     */
    public void setFloat2(Float float2) {
        this.float2 = float2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float3
     *
     * @return the value of container.float3
     *
     * @mbggenerated
     */
    public Float getFloat3() {
        return float3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float3
     *
     * @param float3 the value for container.float3
     *
     * @mbggenerated
     */
    public void setFloat3(Float float3) {
        this.float3 = float3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float4
     *
     * @return the value of container.float4
     *
     * @mbggenerated
     */
    public Float getFloat4() {
        return float4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float4
     *
     * @param float4 the value for container.float4
     *
     * @mbggenerated
     */
    public void setFloat4(Float float4) {
        this.float4 = float4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float5
     *
     * @return the value of container.float5
     *
     * @mbggenerated
     */
    public Float getFloat5() {
        return float5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float5
     *
     * @param float5 the value for container.float5
     *
     * @mbggenerated
     */
    public void setFloat5(Float float5) {
        this.float5 = float5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float6
     *
     * @return the value of container.float6
     *
     * @mbggenerated
     */
    public Float getFloat6() {
        return float6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float6
     *
     * @param float6 the value for container.float6
     *
     * @mbggenerated
     */
    public void setFloat6(Float float6) {
        this.float6 = float6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float7
     *
     * @return the value of container.float7
     *
     * @mbggenerated
     */
    public Float getFloat7() {
        return float7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float7
     *
     * @param float7 the value for container.float7
     *
     * @mbggenerated
     */
    public void setFloat7(Float float7) {
        this.float7 = float7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float8
     *
     * @return the value of container.float8
     *
     * @mbggenerated
     */
    public Float getFloat8() {
        return float8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float8
     *
     * @param float8 the value for container.float8
     *
     * @mbggenerated
     */
    public void setFloat8(Float float8) {
        this.float8 = float8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float9
     *
     * @return the value of container.float9
     *
     * @mbggenerated
     */
    public Float getFloat9() {
        return float9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float9
     *
     * @param float9 the value for container.float9
     *
     * @mbggenerated
     */
    public void setFloat9(Float float9) {
        this.float9 = float9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.float10
     *
     * @return the value of container.float10
     *
     * @mbggenerated
     */
    public Float getFloat10() {
        return float10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.float10
     *
     * @param float10 the value for container.float10
     *
     * @mbggenerated
     */
    public void setFloat10(Float float10) {
        this.float10 = float10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", container_id=").append(container_id);
        sb.append(", created=").append(created);
        sb.append(", modified=").append(modified);
        sb.append(", creatorid=").append(creatorid);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", domain_id=").append(domain_id);
        sb.append(", isavailable=").append(isavailable);
        sb.append(", int1=").append(int1);
        sb.append(", int2=").append(int2);
        sb.append(", int3=").append(int3);
        sb.append(", int4=").append(int4);
        sb.append(", int5=").append(int5);
        sb.append(", int6=").append(int6);
        sb.append(", int7=").append(int7);
        sb.append(", int8=").append(int8);
        sb.append(", int9=").append(int9);
        sb.append(", int10=").append(int10);
        sb.append(", date1=").append(date1);
        sb.append(", date2=").append(date2);
        sb.append(", date3=").append(date3);
        sb.append(", date4=").append(date4);
        sb.append(", date5=").append(date5);
        sb.append(", date6=").append(date6);
        sb.append(", date7=").append(date7);
        sb.append(", date8=").append(date8);
        sb.append(", date9=").append(date9);
        sb.append(", date10=").append(date10);
        sb.append(", float1=").append(float1);
        sb.append(", float2=").append(float2);
        sb.append(", float3=").append(float3);
        sb.append(", float4=").append(float4);
        sb.append(", float5=").append(float5);
        sb.append(", float6=").append(float6);
        sb.append(", float7=").append(float7);
        sb.append(", float8=").append(float8);
        sb.append(", float9=").append(float9);
        sb.append(", float10=").append(float10);
        sb.append("]");
        return sb.toString();
    }
}