package com.megalink.study.model.nochange;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContainerExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table container
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table container
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table container
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public ContainerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table container
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContainer_idIsNull() {
            addCriterion("container_id is null");
            return (Criteria) this;
        }

        public Criteria andContainer_idIsNotNull() {
            addCriterion("container_id is not null");
            return (Criteria) this;
        }

        public Criteria andContainer_idEqualTo(Long value) {
            addCriterion("container_id =", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotEqualTo(Long value) {
            addCriterion("container_id <>", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idGreaterThan(Long value) {
            addCriterion("container_id >", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idGreaterThanOrEqualTo(Long value) {
            addCriterion("container_id >=", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idLessThan(Long value) {
            addCriterion("container_id <", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idLessThanOrEqualTo(Long value) {
            addCriterion("container_id <=", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idIn(List<Long> values) {
            addCriterion("container_id in", values, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotIn(List<Long> values) {
            addCriterion("container_id not in", values, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idBetween(Long value1, Long value2) {
            addCriterion("container_id between", value1, value2, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotBetween(Long value1, Long value2) {
            addCriterion("container_id not between", value1, value2, "container_id");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("creatorid is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("creatorid is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("creatorid =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("creatorid <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("creatorid >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("creatorid >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("creatorid <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("creatorid <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("creatorid like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("creatorid not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("creatorid in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("creatorid not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("creatorid between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("creatorid not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDomain_idIsNull() {
            addCriterion("domain_id is null");
            return (Criteria) this;
        }

        public Criteria andDomain_idIsNotNull() {
            addCriterion("domain_id is not null");
            return (Criteria) this;
        }

        public Criteria andDomain_idEqualTo(Long value) {
            addCriterion("domain_id =", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idNotEqualTo(Long value) {
            addCriterion("domain_id <>", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idGreaterThan(Long value) {
            addCriterion("domain_id >", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idGreaterThanOrEqualTo(Long value) {
            addCriterion("domain_id >=", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idLessThan(Long value) {
            addCriterion("domain_id <", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idLessThanOrEqualTo(Long value) {
            addCriterion("domain_id <=", value, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idIn(List<Long> values) {
            addCriterion("domain_id in", values, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idNotIn(List<Long> values) {
            addCriterion("domain_id not in", values, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idBetween(Long value1, Long value2) {
            addCriterion("domain_id between", value1, value2, "domain_id");
            return (Criteria) this;
        }

        public Criteria andDomain_idNotBetween(Long value1, Long value2) {
            addCriterion("domain_id not between", value1, value2, "domain_id");
            return (Criteria) this;
        }

        public Criteria andIsavailableIsNull() {
            addCriterion("isavailable is null");
            return (Criteria) this;
        }

        public Criteria andIsavailableIsNotNull() {
            addCriterion("isavailable is not null");
            return (Criteria) this;
        }

        public Criteria andIsavailableEqualTo(BigDecimal value) {
            addCriterion("isavailable =", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotEqualTo(BigDecimal value) {
            addCriterion("isavailable <>", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableGreaterThan(BigDecimal value) {
            addCriterion("isavailable >", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("isavailable >=", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableLessThan(BigDecimal value) {
            addCriterion("isavailable <", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableLessThanOrEqualTo(BigDecimal value) {
            addCriterion("isavailable <=", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableIn(List<BigDecimal> values) {
            addCriterion("isavailable in", values, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotIn(List<BigDecimal> values) {
            addCriterion("isavailable not in", values, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("isavailable between", value1, value2, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("isavailable not between", value1, value2, "isavailable");
            return (Criteria) this;
        }

        public Criteria andInt1IsNull() {
            addCriterion("int1 is null");
            return (Criteria) this;
        }

        public Criteria andInt1IsNotNull() {
            addCriterion("int1 is not null");
            return (Criteria) this;
        }

        public Criteria andInt1EqualTo(Integer value) {
            addCriterion("int1 =", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1NotEqualTo(Integer value) {
            addCriterion("int1 <>", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1GreaterThan(Integer value) {
            addCriterion("int1 >", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1GreaterThanOrEqualTo(Integer value) {
            addCriterion("int1 >=", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1LessThan(Integer value) {
            addCriterion("int1 <", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1LessThanOrEqualTo(Integer value) {
            addCriterion("int1 <=", value, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1In(List<Integer> values) {
            addCriterion("int1 in", values, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1NotIn(List<Integer> values) {
            addCriterion("int1 not in", values, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1Between(Integer value1, Integer value2) {
            addCriterion("int1 between", value1, value2, "int1");
            return (Criteria) this;
        }

        public Criteria andInt1NotBetween(Integer value1, Integer value2) {
            addCriterion("int1 not between", value1, value2, "int1");
            return (Criteria) this;
        }

        public Criteria andInt2IsNull() {
            addCriterion("int2 is null");
            return (Criteria) this;
        }

        public Criteria andInt2IsNotNull() {
            addCriterion("int2 is not null");
            return (Criteria) this;
        }

        public Criteria andInt2EqualTo(Integer value) {
            addCriterion("int2 =", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2NotEqualTo(Integer value) {
            addCriterion("int2 <>", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2GreaterThan(Integer value) {
            addCriterion("int2 >", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2GreaterThanOrEqualTo(Integer value) {
            addCriterion("int2 >=", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2LessThan(Integer value) {
            addCriterion("int2 <", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2LessThanOrEqualTo(Integer value) {
            addCriterion("int2 <=", value, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2In(List<Integer> values) {
            addCriterion("int2 in", values, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2NotIn(List<Integer> values) {
            addCriterion("int2 not in", values, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2Between(Integer value1, Integer value2) {
            addCriterion("int2 between", value1, value2, "int2");
            return (Criteria) this;
        }

        public Criteria andInt2NotBetween(Integer value1, Integer value2) {
            addCriterion("int2 not between", value1, value2, "int2");
            return (Criteria) this;
        }

        public Criteria andInt3IsNull() {
            addCriterion("int3 is null");
            return (Criteria) this;
        }

        public Criteria andInt3IsNotNull() {
            addCriterion("int3 is not null");
            return (Criteria) this;
        }

        public Criteria andInt3EqualTo(Integer value) {
            addCriterion("int3 =", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3NotEqualTo(Integer value) {
            addCriterion("int3 <>", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3GreaterThan(Integer value) {
            addCriterion("int3 >", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3GreaterThanOrEqualTo(Integer value) {
            addCriterion("int3 >=", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3LessThan(Integer value) {
            addCriterion("int3 <", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3LessThanOrEqualTo(Integer value) {
            addCriterion("int3 <=", value, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3In(List<Integer> values) {
            addCriterion("int3 in", values, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3NotIn(List<Integer> values) {
            addCriterion("int3 not in", values, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3Between(Integer value1, Integer value2) {
            addCriterion("int3 between", value1, value2, "int3");
            return (Criteria) this;
        }

        public Criteria andInt3NotBetween(Integer value1, Integer value2) {
            addCriterion("int3 not between", value1, value2, "int3");
            return (Criteria) this;
        }

        public Criteria andInt4IsNull() {
            addCriterion("int4 is null");
            return (Criteria) this;
        }

        public Criteria andInt4IsNotNull() {
            addCriterion("int4 is not null");
            return (Criteria) this;
        }

        public Criteria andInt4EqualTo(Integer value) {
            addCriterion("int4 =", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4NotEqualTo(Integer value) {
            addCriterion("int4 <>", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4GreaterThan(Integer value) {
            addCriterion("int4 >", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4GreaterThanOrEqualTo(Integer value) {
            addCriterion("int4 >=", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4LessThan(Integer value) {
            addCriterion("int4 <", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4LessThanOrEqualTo(Integer value) {
            addCriterion("int4 <=", value, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4In(List<Integer> values) {
            addCriterion("int4 in", values, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4NotIn(List<Integer> values) {
            addCriterion("int4 not in", values, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4Between(Integer value1, Integer value2) {
            addCriterion("int4 between", value1, value2, "int4");
            return (Criteria) this;
        }

        public Criteria andInt4NotBetween(Integer value1, Integer value2) {
            addCriterion("int4 not between", value1, value2, "int4");
            return (Criteria) this;
        }

        public Criteria andInt5IsNull() {
            addCriterion("int5 is null");
            return (Criteria) this;
        }

        public Criteria andInt5IsNotNull() {
            addCriterion("int5 is not null");
            return (Criteria) this;
        }

        public Criteria andInt5EqualTo(Integer value) {
            addCriterion("int5 =", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5NotEqualTo(Integer value) {
            addCriterion("int5 <>", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5GreaterThan(Integer value) {
            addCriterion("int5 >", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5GreaterThanOrEqualTo(Integer value) {
            addCriterion("int5 >=", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5LessThan(Integer value) {
            addCriterion("int5 <", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5LessThanOrEqualTo(Integer value) {
            addCriterion("int5 <=", value, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5In(List<Integer> values) {
            addCriterion("int5 in", values, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5NotIn(List<Integer> values) {
            addCriterion("int5 not in", values, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5Between(Integer value1, Integer value2) {
            addCriterion("int5 between", value1, value2, "int5");
            return (Criteria) this;
        }

        public Criteria andInt5NotBetween(Integer value1, Integer value2) {
            addCriterion("int5 not between", value1, value2, "int5");
            return (Criteria) this;
        }

        public Criteria andInt6IsNull() {
            addCriterion("int6 is null");
            return (Criteria) this;
        }

        public Criteria andInt6IsNotNull() {
            addCriterion("int6 is not null");
            return (Criteria) this;
        }

        public Criteria andInt6EqualTo(Integer value) {
            addCriterion("int6 =", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6NotEqualTo(Integer value) {
            addCriterion("int6 <>", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6GreaterThan(Integer value) {
            addCriterion("int6 >", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6GreaterThanOrEqualTo(Integer value) {
            addCriterion("int6 >=", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6LessThan(Integer value) {
            addCriterion("int6 <", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6LessThanOrEqualTo(Integer value) {
            addCriterion("int6 <=", value, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6In(List<Integer> values) {
            addCriterion("int6 in", values, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6NotIn(List<Integer> values) {
            addCriterion("int6 not in", values, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6Between(Integer value1, Integer value2) {
            addCriterion("int6 between", value1, value2, "int6");
            return (Criteria) this;
        }

        public Criteria andInt6NotBetween(Integer value1, Integer value2) {
            addCriterion("int6 not between", value1, value2, "int6");
            return (Criteria) this;
        }

        public Criteria andInt7IsNull() {
            addCriterion("int7 is null");
            return (Criteria) this;
        }

        public Criteria andInt7IsNotNull() {
            addCriterion("int7 is not null");
            return (Criteria) this;
        }

        public Criteria andInt7EqualTo(Integer value) {
            addCriterion("int7 =", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7NotEqualTo(Integer value) {
            addCriterion("int7 <>", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7GreaterThan(Integer value) {
            addCriterion("int7 >", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7GreaterThanOrEqualTo(Integer value) {
            addCriterion("int7 >=", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7LessThan(Integer value) {
            addCriterion("int7 <", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7LessThanOrEqualTo(Integer value) {
            addCriterion("int7 <=", value, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7In(List<Integer> values) {
            addCriterion("int7 in", values, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7NotIn(List<Integer> values) {
            addCriterion("int7 not in", values, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7Between(Integer value1, Integer value2) {
            addCriterion("int7 between", value1, value2, "int7");
            return (Criteria) this;
        }

        public Criteria andInt7NotBetween(Integer value1, Integer value2) {
            addCriterion("int7 not between", value1, value2, "int7");
            return (Criteria) this;
        }

        public Criteria andInt8IsNull() {
            addCriterion("int8 is null");
            return (Criteria) this;
        }

        public Criteria andInt8IsNotNull() {
            addCriterion("int8 is not null");
            return (Criteria) this;
        }

        public Criteria andInt8EqualTo(Integer value) {
            addCriterion("int8 =", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8NotEqualTo(Integer value) {
            addCriterion("int8 <>", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8GreaterThan(Integer value) {
            addCriterion("int8 >", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8GreaterThanOrEqualTo(Integer value) {
            addCriterion("int8 >=", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8LessThan(Integer value) {
            addCriterion("int8 <", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8LessThanOrEqualTo(Integer value) {
            addCriterion("int8 <=", value, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8In(List<Integer> values) {
            addCriterion("int8 in", values, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8NotIn(List<Integer> values) {
            addCriterion("int8 not in", values, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8Between(Integer value1, Integer value2) {
            addCriterion("int8 between", value1, value2, "int8");
            return (Criteria) this;
        }

        public Criteria andInt8NotBetween(Integer value1, Integer value2) {
            addCriterion("int8 not between", value1, value2, "int8");
            return (Criteria) this;
        }

        public Criteria andInt9IsNull() {
            addCriterion("int9 is null");
            return (Criteria) this;
        }

        public Criteria andInt9IsNotNull() {
            addCriterion("int9 is not null");
            return (Criteria) this;
        }

        public Criteria andInt9EqualTo(Integer value) {
            addCriterion("int9 =", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9NotEqualTo(Integer value) {
            addCriterion("int9 <>", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9GreaterThan(Integer value) {
            addCriterion("int9 >", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9GreaterThanOrEqualTo(Integer value) {
            addCriterion("int9 >=", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9LessThan(Integer value) {
            addCriterion("int9 <", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9LessThanOrEqualTo(Integer value) {
            addCriterion("int9 <=", value, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9In(List<Integer> values) {
            addCriterion("int9 in", values, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9NotIn(List<Integer> values) {
            addCriterion("int9 not in", values, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9Between(Integer value1, Integer value2) {
            addCriterion("int9 between", value1, value2, "int9");
            return (Criteria) this;
        }

        public Criteria andInt9NotBetween(Integer value1, Integer value2) {
            addCriterion("int9 not between", value1, value2, "int9");
            return (Criteria) this;
        }

        public Criteria andInt10IsNull() {
            addCriterion("int10 is null");
            return (Criteria) this;
        }

        public Criteria andInt10IsNotNull() {
            addCriterion("int10 is not null");
            return (Criteria) this;
        }

        public Criteria andInt10EqualTo(Integer value) {
            addCriterion("int10 =", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10NotEqualTo(Integer value) {
            addCriterion("int10 <>", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10GreaterThan(Integer value) {
            addCriterion("int10 >", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10GreaterThanOrEqualTo(Integer value) {
            addCriterion("int10 >=", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10LessThan(Integer value) {
            addCriterion("int10 <", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10LessThanOrEqualTo(Integer value) {
            addCriterion("int10 <=", value, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10In(List<Integer> values) {
            addCriterion("int10 in", values, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10NotIn(List<Integer> values) {
            addCriterion("int10 not in", values, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10Between(Integer value1, Integer value2) {
            addCriterion("int10 between", value1, value2, "int10");
            return (Criteria) this;
        }

        public Criteria andInt10NotBetween(Integer value1, Integer value2) {
            addCriterion("int10 not between", value1, value2, "int10");
            return (Criteria) this;
        }

        public Criteria andDate1IsNull() {
            addCriterion("date1 is null");
            return (Criteria) this;
        }

        public Criteria andDate1IsNotNull() {
            addCriterion("date1 is not null");
            return (Criteria) this;
        }

        public Criteria andDate1EqualTo(Date value) {
            addCriterion("date1 =", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotEqualTo(Date value) {
            addCriterion("date1 <>", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThan(Date value) {
            addCriterion("date1 >", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThanOrEqualTo(Date value) {
            addCriterion("date1 >=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThan(Date value) {
            addCriterion("date1 <", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThanOrEqualTo(Date value) {
            addCriterion("date1 <=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1In(List<Date> values) {
            addCriterion("date1 in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotIn(List<Date> values) {
            addCriterion("date1 not in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1Between(Date value1, Date value2) {
            addCriterion("date1 between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotBetween(Date value1, Date value2) {
            addCriterion("date1 not between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate2IsNull() {
            addCriterion("date2 is null");
            return (Criteria) this;
        }

        public Criteria andDate2IsNotNull() {
            addCriterion("date2 is not null");
            return (Criteria) this;
        }

        public Criteria andDate2EqualTo(Date value) {
            addCriterion("date2 =", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotEqualTo(Date value) {
            addCriterion("date2 <>", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThan(Date value) {
            addCriterion("date2 >", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThanOrEqualTo(Date value) {
            addCriterion("date2 >=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThan(Date value) {
            addCriterion("date2 <", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThanOrEqualTo(Date value) {
            addCriterion("date2 <=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2In(List<Date> values) {
            addCriterion("date2 in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotIn(List<Date> values) {
            addCriterion("date2 not in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2Between(Date value1, Date value2) {
            addCriterion("date2 between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotBetween(Date value1, Date value2) {
            addCriterion("date2 not between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate3IsNull() {
            addCriterion("date3 is null");
            return (Criteria) this;
        }

        public Criteria andDate3IsNotNull() {
            addCriterion("date3 is not null");
            return (Criteria) this;
        }

        public Criteria andDate3EqualTo(Date value) {
            addCriterion("date3 =", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotEqualTo(Date value) {
            addCriterion("date3 <>", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThan(Date value) {
            addCriterion("date3 >", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThanOrEqualTo(Date value) {
            addCriterion("date3 >=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThan(Date value) {
            addCriterion("date3 <", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThanOrEqualTo(Date value) {
            addCriterion("date3 <=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3In(List<Date> values) {
            addCriterion("date3 in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotIn(List<Date> values) {
            addCriterion("date3 not in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3Between(Date value1, Date value2) {
            addCriterion("date3 between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotBetween(Date value1, Date value2) {
            addCriterion("date3 not between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate4IsNull() {
            addCriterion("date4 is null");
            return (Criteria) this;
        }

        public Criteria andDate4IsNotNull() {
            addCriterion("date4 is not null");
            return (Criteria) this;
        }

        public Criteria andDate4EqualTo(Date value) {
            addCriterion("date4 =", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotEqualTo(Date value) {
            addCriterion("date4 <>", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThan(Date value) {
            addCriterion("date4 >", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThanOrEqualTo(Date value) {
            addCriterion("date4 >=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThan(Date value) {
            addCriterion("date4 <", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThanOrEqualTo(Date value) {
            addCriterion("date4 <=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4In(List<Date> values) {
            addCriterion("date4 in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotIn(List<Date> values) {
            addCriterion("date4 not in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4Between(Date value1, Date value2) {
            addCriterion("date4 between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotBetween(Date value1, Date value2) {
            addCriterion("date4 not between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate5IsNull() {
            addCriterion("date5 is null");
            return (Criteria) this;
        }

        public Criteria andDate5IsNotNull() {
            addCriterion("date5 is not null");
            return (Criteria) this;
        }

        public Criteria andDate5EqualTo(Date value) {
            addCriterion("date5 =", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotEqualTo(Date value) {
            addCriterion("date5 <>", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThan(Date value) {
            addCriterion("date5 >", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThanOrEqualTo(Date value) {
            addCriterion("date5 >=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThan(Date value) {
            addCriterion("date5 <", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThanOrEqualTo(Date value) {
            addCriterion("date5 <=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5In(List<Date> values) {
            addCriterion("date5 in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotIn(List<Date> values) {
            addCriterion("date5 not in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5Between(Date value1, Date value2) {
            addCriterion("date5 between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotBetween(Date value1, Date value2) {
            addCriterion("date5 not between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andDate6IsNull() {
            addCriterion("date6 is null");
            return (Criteria) this;
        }

        public Criteria andDate6IsNotNull() {
            addCriterion("date6 is not null");
            return (Criteria) this;
        }

        public Criteria andDate6EqualTo(Date value) {
            addCriterion("date6 =", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6NotEqualTo(Date value) {
            addCriterion("date6 <>", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6GreaterThan(Date value) {
            addCriterion("date6 >", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6GreaterThanOrEqualTo(Date value) {
            addCriterion("date6 >=", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6LessThan(Date value) {
            addCriterion("date6 <", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6LessThanOrEqualTo(Date value) {
            addCriterion("date6 <=", value, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6In(List<Date> values) {
            addCriterion("date6 in", values, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6NotIn(List<Date> values) {
            addCriterion("date6 not in", values, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6Between(Date value1, Date value2) {
            addCriterion("date6 between", value1, value2, "date6");
            return (Criteria) this;
        }

        public Criteria andDate6NotBetween(Date value1, Date value2) {
            addCriterion("date6 not between", value1, value2, "date6");
            return (Criteria) this;
        }

        public Criteria andDate7IsNull() {
            addCriterion("date7 is null");
            return (Criteria) this;
        }

        public Criteria andDate7IsNotNull() {
            addCriterion("date7 is not null");
            return (Criteria) this;
        }

        public Criteria andDate7EqualTo(Date value) {
            addCriterion("date7 =", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7NotEqualTo(Date value) {
            addCriterion("date7 <>", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7GreaterThan(Date value) {
            addCriterion("date7 >", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7GreaterThanOrEqualTo(Date value) {
            addCriterion("date7 >=", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7LessThan(Date value) {
            addCriterion("date7 <", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7LessThanOrEqualTo(Date value) {
            addCriterion("date7 <=", value, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7In(List<Date> values) {
            addCriterion("date7 in", values, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7NotIn(List<Date> values) {
            addCriterion("date7 not in", values, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7Between(Date value1, Date value2) {
            addCriterion("date7 between", value1, value2, "date7");
            return (Criteria) this;
        }

        public Criteria andDate7NotBetween(Date value1, Date value2) {
            addCriterion("date7 not between", value1, value2, "date7");
            return (Criteria) this;
        }

        public Criteria andDate8IsNull() {
            addCriterion("date8 is null");
            return (Criteria) this;
        }

        public Criteria andDate8IsNotNull() {
            addCriterion("date8 is not null");
            return (Criteria) this;
        }

        public Criteria andDate8EqualTo(Date value) {
            addCriterion("date8 =", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8NotEqualTo(Date value) {
            addCriterion("date8 <>", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8GreaterThan(Date value) {
            addCriterion("date8 >", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8GreaterThanOrEqualTo(Date value) {
            addCriterion("date8 >=", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8LessThan(Date value) {
            addCriterion("date8 <", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8LessThanOrEqualTo(Date value) {
            addCriterion("date8 <=", value, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8In(List<Date> values) {
            addCriterion("date8 in", values, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8NotIn(List<Date> values) {
            addCriterion("date8 not in", values, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8Between(Date value1, Date value2) {
            addCriterion("date8 between", value1, value2, "date8");
            return (Criteria) this;
        }

        public Criteria andDate8NotBetween(Date value1, Date value2) {
            addCriterion("date8 not between", value1, value2, "date8");
            return (Criteria) this;
        }

        public Criteria andDate9IsNull() {
            addCriterion("date9 is null");
            return (Criteria) this;
        }

        public Criteria andDate9IsNotNull() {
            addCriterion("date9 is not null");
            return (Criteria) this;
        }

        public Criteria andDate9EqualTo(Date value) {
            addCriterion("date9 =", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9NotEqualTo(Date value) {
            addCriterion("date9 <>", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9GreaterThan(Date value) {
            addCriterion("date9 >", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9GreaterThanOrEqualTo(Date value) {
            addCriterion("date9 >=", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9LessThan(Date value) {
            addCriterion("date9 <", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9LessThanOrEqualTo(Date value) {
            addCriterion("date9 <=", value, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9In(List<Date> values) {
            addCriterion("date9 in", values, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9NotIn(List<Date> values) {
            addCriterion("date9 not in", values, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9Between(Date value1, Date value2) {
            addCriterion("date9 between", value1, value2, "date9");
            return (Criteria) this;
        }

        public Criteria andDate9NotBetween(Date value1, Date value2) {
            addCriterion("date9 not between", value1, value2, "date9");
            return (Criteria) this;
        }

        public Criteria andDate10IsNull() {
            addCriterion("date10 is null");
            return (Criteria) this;
        }

        public Criteria andDate10IsNotNull() {
            addCriterion("date10 is not null");
            return (Criteria) this;
        }

        public Criteria andDate10EqualTo(Date value) {
            addCriterion("date10 =", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10NotEqualTo(Date value) {
            addCriterion("date10 <>", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10GreaterThan(Date value) {
            addCriterion("date10 >", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10GreaterThanOrEqualTo(Date value) {
            addCriterion("date10 >=", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10LessThan(Date value) {
            addCriterion("date10 <", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10LessThanOrEqualTo(Date value) {
            addCriterion("date10 <=", value, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10In(List<Date> values) {
            addCriterion("date10 in", values, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10NotIn(List<Date> values) {
            addCriterion("date10 not in", values, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10Between(Date value1, Date value2) {
            addCriterion("date10 between", value1, value2, "date10");
            return (Criteria) this;
        }

        public Criteria andDate10NotBetween(Date value1, Date value2) {
            addCriterion("date10 not between", value1, value2, "date10");
            return (Criteria) this;
        }

        public Criteria andFloat1IsNull() {
            addCriterion("float1 is null");
            return (Criteria) this;
        }

        public Criteria andFloat1IsNotNull() {
            addCriterion("float1 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat1EqualTo(Float value) {
            addCriterion("float1 =", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1NotEqualTo(Float value) {
            addCriterion("float1 <>", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1GreaterThan(Float value) {
            addCriterion("float1 >", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1GreaterThanOrEqualTo(Float value) {
            addCriterion("float1 >=", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1LessThan(Float value) {
            addCriterion("float1 <", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1LessThanOrEqualTo(Float value) {
            addCriterion("float1 <=", value, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1In(List<Float> values) {
            addCriterion("float1 in", values, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1NotIn(List<Float> values) {
            addCriterion("float1 not in", values, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1Between(Float value1, Float value2) {
            addCriterion("float1 between", value1, value2, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat1NotBetween(Float value1, Float value2) {
            addCriterion("float1 not between", value1, value2, "float1");
            return (Criteria) this;
        }

        public Criteria andFloat2IsNull() {
            addCriterion("float2 is null");
            return (Criteria) this;
        }

        public Criteria andFloat2IsNotNull() {
            addCriterion("float2 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat2EqualTo(Float value) {
            addCriterion("float2 =", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2NotEqualTo(Float value) {
            addCriterion("float2 <>", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2GreaterThan(Float value) {
            addCriterion("float2 >", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2GreaterThanOrEqualTo(Float value) {
            addCriterion("float2 >=", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2LessThan(Float value) {
            addCriterion("float2 <", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2LessThanOrEqualTo(Float value) {
            addCriterion("float2 <=", value, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2In(List<Float> values) {
            addCriterion("float2 in", values, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2NotIn(List<Float> values) {
            addCriterion("float2 not in", values, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2Between(Float value1, Float value2) {
            addCriterion("float2 between", value1, value2, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat2NotBetween(Float value1, Float value2) {
            addCriterion("float2 not between", value1, value2, "float2");
            return (Criteria) this;
        }

        public Criteria andFloat3IsNull() {
            addCriterion("float3 is null");
            return (Criteria) this;
        }

        public Criteria andFloat3IsNotNull() {
            addCriterion("float3 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat3EqualTo(Float value) {
            addCriterion("float3 =", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3NotEqualTo(Float value) {
            addCriterion("float3 <>", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3GreaterThan(Float value) {
            addCriterion("float3 >", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3GreaterThanOrEqualTo(Float value) {
            addCriterion("float3 >=", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3LessThan(Float value) {
            addCriterion("float3 <", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3LessThanOrEqualTo(Float value) {
            addCriterion("float3 <=", value, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3In(List<Float> values) {
            addCriterion("float3 in", values, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3NotIn(List<Float> values) {
            addCriterion("float3 not in", values, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3Between(Float value1, Float value2) {
            addCriterion("float3 between", value1, value2, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat3NotBetween(Float value1, Float value2) {
            addCriterion("float3 not between", value1, value2, "float3");
            return (Criteria) this;
        }

        public Criteria andFloat4IsNull() {
            addCriterion("float4 is null");
            return (Criteria) this;
        }

        public Criteria andFloat4IsNotNull() {
            addCriterion("float4 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat4EqualTo(Float value) {
            addCriterion("float4 =", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4NotEqualTo(Float value) {
            addCriterion("float4 <>", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4GreaterThan(Float value) {
            addCriterion("float4 >", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4GreaterThanOrEqualTo(Float value) {
            addCriterion("float4 >=", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4LessThan(Float value) {
            addCriterion("float4 <", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4LessThanOrEqualTo(Float value) {
            addCriterion("float4 <=", value, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4In(List<Float> values) {
            addCriterion("float4 in", values, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4NotIn(List<Float> values) {
            addCriterion("float4 not in", values, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4Between(Float value1, Float value2) {
            addCriterion("float4 between", value1, value2, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat4NotBetween(Float value1, Float value2) {
            addCriterion("float4 not between", value1, value2, "float4");
            return (Criteria) this;
        }

        public Criteria andFloat5IsNull() {
            addCriterion("float5 is null");
            return (Criteria) this;
        }

        public Criteria andFloat5IsNotNull() {
            addCriterion("float5 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat5EqualTo(Float value) {
            addCriterion("float5 =", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5NotEqualTo(Float value) {
            addCriterion("float5 <>", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5GreaterThan(Float value) {
            addCriterion("float5 >", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5GreaterThanOrEqualTo(Float value) {
            addCriterion("float5 >=", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5LessThan(Float value) {
            addCriterion("float5 <", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5LessThanOrEqualTo(Float value) {
            addCriterion("float5 <=", value, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5In(List<Float> values) {
            addCriterion("float5 in", values, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5NotIn(List<Float> values) {
            addCriterion("float5 not in", values, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5Between(Float value1, Float value2) {
            addCriterion("float5 between", value1, value2, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat5NotBetween(Float value1, Float value2) {
            addCriterion("float5 not between", value1, value2, "float5");
            return (Criteria) this;
        }

        public Criteria andFloat6IsNull() {
            addCriterion("float6 is null");
            return (Criteria) this;
        }

        public Criteria andFloat6IsNotNull() {
            addCriterion("float6 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat6EqualTo(Float value) {
            addCriterion("float6 =", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6NotEqualTo(Float value) {
            addCriterion("float6 <>", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6GreaterThan(Float value) {
            addCriterion("float6 >", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6GreaterThanOrEqualTo(Float value) {
            addCriterion("float6 >=", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6LessThan(Float value) {
            addCriterion("float6 <", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6LessThanOrEqualTo(Float value) {
            addCriterion("float6 <=", value, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6In(List<Float> values) {
            addCriterion("float6 in", values, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6NotIn(List<Float> values) {
            addCriterion("float6 not in", values, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6Between(Float value1, Float value2) {
            addCriterion("float6 between", value1, value2, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat6NotBetween(Float value1, Float value2) {
            addCriterion("float6 not between", value1, value2, "float6");
            return (Criteria) this;
        }

        public Criteria andFloat7IsNull() {
            addCriterion("float7 is null");
            return (Criteria) this;
        }

        public Criteria andFloat7IsNotNull() {
            addCriterion("float7 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat7EqualTo(Float value) {
            addCriterion("float7 =", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7NotEqualTo(Float value) {
            addCriterion("float7 <>", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7GreaterThan(Float value) {
            addCriterion("float7 >", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7GreaterThanOrEqualTo(Float value) {
            addCriterion("float7 >=", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7LessThan(Float value) {
            addCriterion("float7 <", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7LessThanOrEqualTo(Float value) {
            addCriterion("float7 <=", value, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7In(List<Float> values) {
            addCriterion("float7 in", values, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7NotIn(List<Float> values) {
            addCriterion("float7 not in", values, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7Between(Float value1, Float value2) {
            addCriterion("float7 between", value1, value2, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat7NotBetween(Float value1, Float value2) {
            addCriterion("float7 not between", value1, value2, "float7");
            return (Criteria) this;
        }

        public Criteria andFloat8IsNull() {
            addCriterion("float8 is null");
            return (Criteria) this;
        }

        public Criteria andFloat8IsNotNull() {
            addCriterion("float8 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat8EqualTo(Float value) {
            addCriterion("float8 =", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8NotEqualTo(Float value) {
            addCriterion("float8 <>", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8GreaterThan(Float value) {
            addCriterion("float8 >", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8GreaterThanOrEqualTo(Float value) {
            addCriterion("float8 >=", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8LessThan(Float value) {
            addCriterion("float8 <", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8LessThanOrEqualTo(Float value) {
            addCriterion("float8 <=", value, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8In(List<Float> values) {
            addCriterion("float8 in", values, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8NotIn(List<Float> values) {
            addCriterion("float8 not in", values, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8Between(Float value1, Float value2) {
            addCriterion("float8 between", value1, value2, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat8NotBetween(Float value1, Float value2) {
            addCriterion("float8 not between", value1, value2, "float8");
            return (Criteria) this;
        }

        public Criteria andFloat9IsNull() {
            addCriterion("float9 is null");
            return (Criteria) this;
        }

        public Criteria andFloat9IsNotNull() {
            addCriterion("float9 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat9EqualTo(Float value) {
            addCriterion("float9 =", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9NotEqualTo(Float value) {
            addCriterion("float9 <>", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9GreaterThan(Float value) {
            addCriterion("float9 >", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9GreaterThanOrEqualTo(Float value) {
            addCriterion("float9 >=", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9LessThan(Float value) {
            addCriterion("float9 <", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9LessThanOrEqualTo(Float value) {
            addCriterion("float9 <=", value, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9In(List<Float> values) {
            addCriterion("float9 in", values, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9NotIn(List<Float> values) {
            addCriterion("float9 not in", values, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9Between(Float value1, Float value2) {
            addCriterion("float9 between", value1, value2, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat9NotBetween(Float value1, Float value2) {
            addCriterion("float9 not between", value1, value2, "float9");
            return (Criteria) this;
        }

        public Criteria andFloat10IsNull() {
            addCriterion("float10 is null");
            return (Criteria) this;
        }

        public Criteria andFloat10IsNotNull() {
            addCriterion("float10 is not null");
            return (Criteria) this;
        }

        public Criteria andFloat10EqualTo(Float value) {
            addCriterion("float10 =", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10NotEqualTo(Float value) {
            addCriterion("float10 <>", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10GreaterThan(Float value) {
            addCriterion("float10 >", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10GreaterThanOrEqualTo(Float value) {
            addCriterion("float10 >=", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10LessThan(Float value) {
            addCriterion("float10 <", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10LessThanOrEqualTo(Float value) {
            addCriterion("float10 <=", value, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10In(List<Float> values) {
            addCriterion("float10 in", values, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10NotIn(List<Float> values) {
            addCriterion("float10 not in", values, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10Between(Float value1, Float value2) {
            addCriterion("float10 between", value1, value2, "float10");
            return (Criteria) this;
        }

        public Criteria andFloat10NotBetween(Float value1, Float value2) {
            addCriterion("float10 not between", value1, value2, "float10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table container
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table container
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}