package com.megalink.study.model.nochange;

public class ContainerWithBLOBs extends Container {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field5
     *
     * @mbggenerated
     */
    private String field5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field6
     *
     * @mbggenerated
     */
    private String field6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field7
     *
     * @mbggenerated
     */
    private String field7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field8
     *
     * @mbggenerated
     */
    private String field8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field9
     *
     * @mbggenerated
     */
    private String field9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field10
     *
     * @mbggenerated
     */
    private String field10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field11
     *
     * @mbggenerated
     */
    private String field11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field12
     *
     * @mbggenerated
     */
    private String field12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field13
     *
     * @mbggenerated
     */
    private String field13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field14
     *
     * @mbggenerated
     */
    private String field14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field15
     *
     * @mbggenerated
     */
    private String field15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field16
     *
     * @mbggenerated
     */
    private String field16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field17
     *
     * @mbggenerated
     */
    private String field17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field18
     *
     * @mbggenerated
     */
    private String field18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field19
     *
     * @mbggenerated
     */
    private String field19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container.field20
     *
     * @mbggenerated
     */
    private String field20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field1
     *
     * @return the value of container.field1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field1
     *
     * @param field1 the value for container.field1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field2
     *
     * @return the value of container.field2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field2
     *
     * @param field2 the value for container.field2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field3
     *
     * @return the value of container.field3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field3
     *
     * @param field3 the value for container.field3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field4
     *
     * @return the value of container.field4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field4
     *
     * @param field4 the value for container.field4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field5
     *
     * @return the value of container.field5
     *
     * @mbggenerated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field5
     *
     * @param field5 the value for container.field5
     *
     * @mbggenerated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field6
     *
     * @return the value of container.field6
     *
     * @mbggenerated
     */
    public String getField6() {
        return field6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field6
     *
     * @param field6 the value for container.field6
     *
     * @mbggenerated
     */
    public void setField6(String field6) {
        this.field6 = field6 == null ? null : field6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field7
     *
     * @return the value of container.field7
     *
     * @mbggenerated
     */
    public String getField7() {
        return field7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field7
     *
     * @param field7 the value for container.field7
     *
     * @mbggenerated
     */
    public void setField7(String field7) {
        this.field7 = field7 == null ? null : field7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field8
     *
     * @return the value of container.field8
     *
     * @mbggenerated
     */
    public String getField8() {
        return field8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field8
     *
     * @param field8 the value for container.field8
     *
     * @mbggenerated
     */
    public void setField8(String field8) {
        this.field8 = field8 == null ? null : field8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field9
     *
     * @return the value of container.field9
     *
     * @mbggenerated
     */
    public String getField9() {
        return field9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field9
     *
     * @param field9 the value for container.field9
     *
     * @mbggenerated
     */
    public void setField9(String field9) {
        this.field9 = field9 == null ? null : field9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field10
     *
     * @return the value of container.field10
     *
     * @mbggenerated
     */
    public String getField10() {
        return field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field10
     *
     * @param field10 the value for container.field10
     *
     * @mbggenerated
     */
    public void setField10(String field10) {
        this.field10 = field10 == null ? null : field10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field11
     *
     * @return the value of container.field11
     *
     * @mbggenerated
     */
    public String getField11() {
        return field11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field11
     *
     * @param field11 the value for container.field11
     *
     * @mbggenerated
     */
    public void setField11(String field11) {
        this.field11 = field11 == null ? null : field11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field12
     *
     * @return the value of container.field12
     *
     * @mbggenerated
     */
    public String getField12() {
        return field12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field12
     *
     * @param field12 the value for container.field12
     *
     * @mbggenerated
     */
    public void setField12(String field12) {
        this.field12 = field12 == null ? null : field12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field13
     *
     * @return the value of container.field13
     *
     * @mbggenerated
     */
    public String getField13() {
        return field13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field13
     *
     * @param field13 the value for container.field13
     *
     * @mbggenerated
     */
    public void setField13(String field13) {
        this.field13 = field13 == null ? null : field13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field14
     *
     * @return the value of container.field14
     *
     * @mbggenerated
     */
    public String getField14() {
        return field14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field14
     *
     * @param field14 the value for container.field14
     *
     * @mbggenerated
     */
    public void setField14(String field14) {
        this.field14 = field14 == null ? null : field14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field15
     *
     * @return the value of container.field15
     *
     * @mbggenerated
     */
    public String getField15() {
        return field15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field15
     *
     * @param field15 the value for container.field15
     *
     * @mbggenerated
     */
    public void setField15(String field15) {
        this.field15 = field15 == null ? null : field15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field16
     *
     * @return the value of container.field16
     *
     * @mbggenerated
     */
    public String getField16() {
        return field16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field16
     *
     * @param field16 the value for container.field16
     *
     * @mbggenerated
     */
    public void setField16(String field16) {
        this.field16 = field16 == null ? null : field16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field17
     *
     * @return the value of container.field17
     *
     * @mbggenerated
     */
    public String getField17() {
        return field17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field17
     *
     * @param field17 the value for container.field17
     *
     * @mbggenerated
     */
    public void setField17(String field17) {
        this.field17 = field17 == null ? null : field17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field18
     *
     * @return the value of container.field18
     *
     * @mbggenerated
     */
    public String getField18() {
        return field18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field18
     *
     * @param field18 the value for container.field18
     *
     * @mbggenerated
     */
    public void setField18(String field18) {
        this.field18 = field18 == null ? null : field18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field19
     *
     * @return the value of container.field19
     *
     * @mbggenerated
     */
    public String getField19() {
        return field19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field19
     *
     * @param field19 the value for container.field19
     *
     * @mbggenerated
     */
    public void setField19(String field19) {
        this.field19 = field19 == null ? null : field19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container.field20
     *
     * @return the value of container.field20
     *
     * @mbggenerated
     */
    public String getField20() {
        return field20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container.field20
     *
     * @param field20 the value for container.field20
     *
     * @mbggenerated
     */
    public void setField20(String field20) {
        this.field20 = field20 == null ? null : field20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", field1=").append(field1);
        sb.append(", field2=").append(field2);
        sb.append(", field3=").append(field3);
        sb.append(", field4=").append(field4);
        sb.append(", field5=").append(field5);
        sb.append(", field6=").append(field6);
        sb.append(", field7=").append(field7);
        sb.append(", field8=").append(field8);
        sb.append(", field9=").append(field9);
        sb.append(", field10=").append(field10);
        sb.append(", field11=").append(field11);
        sb.append(", field12=").append(field12);
        sb.append(", field13=").append(field13);
        sb.append(", field14=").append(field14);
        sb.append(", field15=").append(field15);
        sb.append(", field16=").append(field16);
        sb.append(", field17=").append(field17);
        sb.append(", field18=").append(field18);
        sb.append(", field19=").append(field19);
        sb.append(", field20=").append(field20);
        sb.append("]");
        return sb.toString();
    }
}