package com.megalink.study.model.nochange;

import java.util.Date;

public class Folder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FOLDER_ID
     *
     * @mbggenerated
     */
    private Long FOLDER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.CREATED
     *
     * @mbggenerated
     */
    private Date CREATED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.MODIFIED
     *
     * @mbggenerated
     */
    private Date MODIFIED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.CREATORID
     *
     * @mbggenerated
     */
    private String CREATORID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FOLDER_NAME
     *
     * @mbggenerated
     */
    private String FOLDER_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.PARENT_FOLDER_ID
     *
     * @mbggenerated
     */
    private Long PARENT_FOLDER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.CONTAINER_ID
     *
     * @mbggenerated
     */
    private Long CONTAINER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FOLDER_PATH
     *
     * @mbggenerated
     */
    private String FOLDER_PATH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DOMAIN_ID
     *
     * @mbggenerated
     */
    private Long DOMAIN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT1
     *
     * @mbggenerated
     */
    private Integer INT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT2
     *
     * @mbggenerated
     */
    private Integer INT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT3
     *
     * @mbggenerated
     */
    private Integer INT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT4
     *
     * @mbggenerated
     */
    private Integer INT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT5
     *
     * @mbggenerated
     */
    private Integer INT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT6
     *
     * @mbggenerated
     */
    private Integer INT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT7
     *
     * @mbggenerated
     */
    private Integer INT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT8
     *
     * @mbggenerated
     */
    private Integer INT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT9
     *
     * @mbggenerated
     */
    private Integer INT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.INT10
     *
     * @mbggenerated
     */
    private Integer INT10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE1
     *
     * @mbggenerated
     */
    private Date DATE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE2
     *
     * @mbggenerated
     */
    private Date DATE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE3
     *
     * @mbggenerated
     */
    private Date DATE3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE4
     *
     * @mbggenerated
     */
    private Date DATE4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE5
     *
     * @mbggenerated
     */
    private Date DATE5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE6
     *
     * @mbggenerated
     */
    private Date DATE6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE7
     *
     * @mbggenerated
     */
    private Date DATE7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE8
     *
     * @mbggenerated
     */
    private Date DATE8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE9
     *
     * @mbggenerated
     */
    private Date DATE9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.DATE10
     *
     * @mbggenerated
     */
    private Date DATE10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT1
     *
     * @mbggenerated
     */
    private Float FLOAT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT2
     *
     * @mbggenerated
     */
    private Float FLOAT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT3
     *
     * @mbggenerated
     */
    private Float FLOAT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT4
     *
     * @mbggenerated
     */
    private Float FLOAT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT5
     *
     * @mbggenerated
     */
    private Float FLOAT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT6
     *
     * @mbggenerated
     */
    private Float FLOAT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT7
     *
     * @mbggenerated
     */
    private Float FLOAT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT8
     *
     * @mbggenerated
     */
    private Float FLOAT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT9
     *
     * @mbggenerated
     */
    private Float FLOAT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.FLOAT10
     *
     * @mbggenerated
     */
    private Float FLOAT10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FOLDER_ID
     *
     * @return the value of folder.FOLDER_ID
     *
     * @mbggenerated
     */
    public Long getFOLDER_ID() {
        return FOLDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FOLDER_ID
     *
     * @param FOLDER_ID the value for folder.FOLDER_ID
     *
     * @mbggenerated
     */
    public void setFOLDER_ID(Long FOLDER_ID) {
        this.FOLDER_ID = FOLDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.CREATED
     *
     * @return the value of folder.CREATED
     *
     * @mbggenerated
     */
    public Date getCREATED() {
        return CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.CREATED
     *
     * @param CREATED the value for folder.CREATED
     *
     * @mbggenerated
     */
    public void setCREATED(Date CREATED) {
        this.CREATED = CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.MODIFIED
     *
     * @return the value of folder.MODIFIED
     *
     * @mbggenerated
     */
    public Date getMODIFIED() {
        return MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.MODIFIED
     *
     * @param MODIFIED the value for folder.MODIFIED
     *
     * @mbggenerated
     */
    public void setMODIFIED(Date MODIFIED) {
        this.MODIFIED = MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.CREATORID
     *
     * @return the value of folder.CREATORID
     *
     * @mbggenerated
     */
    public String getCREATORID() {
        return CREATORID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.CREATORID
     *
     * @param CREATORID the value for folder.CREATORID
     *
     * @mbggenerated
     */
    public void setCREATORID(String CREATORID) {
        this.CREATORID = CREATORID == null ? null : CREATORID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FOLDER_NAME
     *
     * @return the value of folder.FOLDER_NAME
     *
     * @mbggenerated
     */
    public String getFOLDER_NAME() {
        return FOLDER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FOLDER_NAME
     *
     * @param FOLDER_NAME the value for folder.FOLDER_NAME
     *
     * @mbggenerated
     */
    public void setFOLDER_NAME(String FOLDER_NAME) {
        this.FOLDER_NAME = FOLDER_NAME == null ? null : FOLDER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.PARENT_FOLDER_ID
     *
     * @return the value of folder.PARENT_FOLDER_ID
     *
     * @mbggenerated
     */
    public Long getPARENT_FOLDER_ID() {
        return PARENT_FOLDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.PARENT_FOLDER_ID
     *
     * @param PARENT_FOLDER_ID the value for folder.PARENT_FOLDER_ID
     *
     * @mbggenerated
     */
    public void setPARENT_FOLDER_ID(Long PARENT_FOLDER_ID) {
        this.PARENT_FOLDER_ID = PARENT_FOLDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.CONTAINER_ID
     *
     * @return the value of folder.CONTAINER_ID
     *
     * @mbggenerated
     */
    public Long getCONTAINER_ID() {
        return CONTAINER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.CONTAINER_ID
     *
     * @param CONTAINER_ID the value for folder.CONTAINER_ID
     *
     * @mbggenerated
     */
    public void setCONTAINER_ID(Long CONTAINER_ID) {
        this.CONTAINER_ID = CONTAINER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FOLDER_PATH
     *
     * @return the value of folder.FOLDER_PATH
     *
     * @mbggenerated
     */
    public String getFOLDER_PATH() {
        return FOLDER_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FOLDER_PATH
     *
     * @param FOLDER_PATH the value for folder.FOLDER_PATH
     *
     * @mbggenerated
     */
    public void setFOLDER_PATH(String FOLDER_PATH) {
        this.FOLDER_PATH = FOLDER_PATH == null ? null : FOLDER_PATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DOMAIN_ID
     *
     * @return the value of folder.DOMAIN_ID
     *
     * @mbggenerated
     */
    public Long getDOMAIN_ID() {
        return DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DOMAIN_ID
     *
     * @param DOMAIN_ID the value for folder.DOMAIN_ID
     *
     * @mbggenerated
     */
    public void setDOMAIN_ID(Long DOMAIN_ID) {
        this.DOMAIN_ID = DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT1
     *
     * @return the value of folder.INT1
     *
     * @mbggenerated
     */
    public Integer getINT1() {
        return INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT1
     *
     * @param INT1 the value for folder.INT1
     *
     * @mbggenerated
     */
    public void setINT1(Integer INT1) {
        this.INT1 = INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT2
     *
     * @return the value of folder.INT2
     *
     * @mbggenerated
     */
    public Integer getINT2() {
        return INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT2
     *
     * @param INT2 the value for folder.INT2
     *
     * @mbggenerated
     */
    public void setINT2(Integer INT2) {
        this.INT2 = INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT3
     *
     * @return the value of folder.INT3
     *
     * @mbggenerated
     */
    public Integer getINT3() {
        return INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT3
     *
     * @param INT3 the value for folder.INT3
     *
     * @mbggenerated
     */
    public void setINT3(Integer INT3) {
        this.INT3 = INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT4
     *
     * @return the value of folder.INT4
     *
     * @mbggenerated
     */
    public Integer getINT4() {
        return INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT4
     *
     * @param INT4 the value for folder.INT4
     *
     * @mbggenerated
     */
    public void setINT4(Integer INT4) {
        this.INT4 = INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT5
     *
     * @return the value of folder.INT5
     *
     * @mbggenerated
     */
    public Integer getINT5() {
        return INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT5
     *
     * @param INT5 the value for folder.INT5
     *
     * @mbggenerated
     */
    public void setINT5(Integer INT5) {
        this.INT5 = INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT6
     *
     * @return the value of folder.INT6
     *
     * @mbggenerated
     */
    public Integer getINT6() {
        return INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT6
     *
     * @param INT6 the value for folder.INT6
     *
     * @mbggenerated
     */
    public void setINT6(Integer INT6) {
        this.INT6 = INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT7
     *
     * @return the value of folder.INT7
     *
     * @mbggenerated
     */
    public Integer getINT7() {
        return INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT7
     *
     * @param INT7 the value for folder.INT7
     *
     * @mbggenerated
     */
    public void setINT7(Integer INT7) {
        this.INT7 = INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT8
     *
     * @return the value of folder.INT8
     *
     * @mbggenerated
     */
    public Integer getINT8() {
        return INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT8
     *
     * @param INT8 the value for folder.INT8
     *
     * @mbggenerated
     */
    public void setINT8(Integer INT8) {
        this.INT8 = INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT9
     *
     * @return the value of folder.INT9
     *
     * @mbggenerated
     */
    public Integer getINT9() {
        return INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT9
     *
     * @param INT9 the value for folder.INT9
     *
     * @mbggenerated
     */
    public void setINT9(Integer INT9) {
        this.INT9 = INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.INT10
     *
     * @return the value of folder.INT10
     *
     * @mbggenerated
     */
    public Integer getINT10() {
        return INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.INT10
     *
     * @param INT10 the value for folder.INT10
     *
     * @mbggenerated
     */
    public void setINT10(Integer INT10) {
        this.INT10 = INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE1
     *
     * @return the value of folder.DATE1
     *
     * @mbggenerated
     */
    public Date getDATE1() {
        return DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE1
     *
     * @param DATE1 the value for folder.DATE1
     *
     * @mbggenerated
     */
    public void setDATE1(Date DATE1) {
        this.DATE1 = DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE2
     *
     * @return the value of folder.DATE2
     *
     * @mbggenerated
     */
    public Date getDATE2() {
        return DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE2
     *
     * @param DATE2 the value for folder.DATE2
     *
     * @mbggenerated
     */
    public void setDATE2(Date DATE2) {
        this.DATE2 = DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE3
     *
     * @return the value of folder.DATE3
     *
     * @mbggenerated
     */
    public Date getDATE3() {
        return DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE3
     *
     * @param DATE3 the value for folder.DATE3
     *
     * @mbggenerated
     */
    public void setDATE3(Date DATE3) {
        this.DATE3 = DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE4
     *
     * @return the value of folder.DATE4
     *
     * @mbggenerated
     */
    public Date getDATE4() {
        return DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE4
     *
     * @param DATE4 the value for folder.DATE4
     *
     * @mbggenerated
     */
    public void setDATE4(Date DATE4) {
        this.DATE4 = DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE5
     *
     * @return the value of folder.DATE5
     *
     * @mbggenerated
     */
    public Date getDATE5() {
        return DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE5
     *
     * @param DATE5 the value for folder.DATE5
     *
     * @mbggenerated
     */
    public void setDATE5(Date DATE5) {
        this.DATE5 = DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE6
     *
     * @return the value of folder.DATE6
     *
     * @mbggenerated
     */
    public Date getDATE6() {
        return DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE6
     *
     * @param DATE6 the value for folder.DATE6
     *
     * @mbggenerated
     */
    public void setDATE6(Date DATE6) {
        this.DATE6 = DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE7
     *
     * @return the value of folder.DATE7
     *
     * @mbggenerated
     */
    public Date getDATE7() {
        return DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE7
     *
     * @param DATE7 the value for folder.DATE7
     *
     * @mbggenerated
     */
    public void setDATE7(Date DATE7) {
        this.DATE7 = DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE8
     *
     * @return the value of folder.DATE8
     *
     * @mbggenerated
     */
    public Date getDATE8() {
        return DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE8
     *
     * @param DATE8 the value for folder.DATE8
     *
     * @mbggenerated
     */
    public void setDATE8(Date DATE8) {
        this.DATE8 = DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE9
     *
     * @return the value of folder.DATE9
     *
     * @mbggenerated
     */
    public Date getDATE9() {
        return DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE9
     *
     * @param DATE9 the value for folder.DATE9
     *
     * @mbggenerated
     */
    public void setDATE9(Date DATE9) {
        this.DATE9 = DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.DATE10
     *
     * @return the value of folder.DATE10
     *
     * @mbggenerated
     */
    public Date getDATE10() {
        return DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.DATE10
     *
     * @param DATE10 the value for folder.DATE10
     *
     * @mbggenerated
     */
    public void setDATE10(Date DATE10) {
        this.DATE10 = DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT1
     *
     * @return the value of folder.FLOAT1
     *
     * @mbggenerated
     */
    public Float getFLOAT1() {
        return FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT1
     *
     * @param FLOAT1 the value for folder.FLOAT1
     *
     * @mbggenerated
     */
    public void setFLOAT1(Float FLOAT1) {
        this.FLOAT1 = FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT2
     *
     * @return the value of folder.FLOAT2
     *
     * @mbggenerated
     */
    public Float getFLOAT2() {
        return FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT2
     *
     * @param FLOAT2 the value for folder.FLOAT2
     *
     * @mbggenerated
     */
    public void setFLOAT2(Float FLOAT2) {
        this.FLOAT2 = FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT3
     *
     * @return the value of folder.FLOAT3
     *
     * @mbggenerated
     */
    public Float getFLOAT3() {
        return FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT3
     *
     * @param FLOAT3 the value for folder.FLOAT3
     *
     * @mbggenerated
     */
    public void setFLOAT3(Float FLOAT3) {
        this.FLOAT3 = FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT4
     *
     * @return the value of folder.FLOAT4
     *
     * @mbggenerated
     */
    public Float getFLOAT4() {
        return FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT4
     *
     * @param FLOAT4 the value for folder.FLOAT4
     *
     * @mbggenerated
     */
    public void setFLOAT4(Float FLOAT4) {
        this.FLOAT4 = FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT5
     *
     * @return the value of folder.FLOAT5
     *
     * @mbggenerated
     */
    public Float getFLOAT5() {
        return FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT5
     *
     * @param FLOAT5 the value for folder.FLOAT5
     *
     * @mbggenerated
     */
    public void setFLOAT5(Float FLOAT5) {
        this.FLOAT5 = FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT6
     *
     * @return the value of folder.FLOAT6
     *
     * @mbggenerated
     */
    public Float getFLOAT6() {
        return FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT6
     *
     * @param FLOAT6 the value for folder.FLOAT6
     *
     * @mbggenerated
     */
    public void setFLOAT6(Float FLOAT6) {
        this.FLOAT6 = FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT7
     *
     * @return the value of folder.FLOAT7
     *
     * @mbggenerated
     */
    public Float getFLOAT7() {
        return FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT7
     *
     * @param FLOAT7 the value for folder.FLOAT7
     *
     * @mbggenerated
     */
    public void setFLOAT7(Float FLOAT7) {
        this.FLOAT7 = FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT8
     *
     * @return the value of folder.FLOAT8
     *
     * @mbggenerated
     */
    public Float getFLOAT8() {
        return FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT8
     *
     * @param FLOAT8 the value for folder.FLOAT8
     *
     * @mbggenerated
     */
    public void setFLOAT8(Float FLOAT8) {
        this.FLOAT8 = FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT9
     *
     * @return the value of folder.FLOAT9
     *
     * @mbggenerated
     */
    public Float getFLOAT9() {
        return FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT9
     *
     * @param FLOAT9 the value for folder.FLOAT9
     *
     * @mbggenerated
     */
    public void setFLOAT9(Float FLOAT9) {
        this.FLOAT9 = FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.FLOAT10
     *
     * @return the value of folder.FLOAT10
     *
     * @mbggenerated
     */
    public Float getFLOAT10() {
        return FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.FLOAT10
     *
     * @param FLOAT10 the value for folder.FLOAT10
     *
     * @mbggenerated
     */
    public void setFLOAT10(Float FLOAT10) {
        this.FLOAT10 = FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", FOLDER_ID=").append(FOLDER_ID);
        sb.append(", CREATED=").append(CREATED);
        sb.append(", MODIFIED=").append(MODIFIED);
        sb.append(", CREATORID=").append(CREATORID);
        sb.append(", FOLDER_NAME=").append(FOLDER_NAME);
        sb.append(", PARENT_FOLDER_ID=").append(PARENT_FOLDER_ID);
        sb.append(", CONTAINER_ID=").append(CONTAINER_ID);
        sb.append(", FOLDER_PATH=").append(FOLDER_PATH);
        sb.append(", DOMAIN_ID=").append(DOMAIN_ID);
        sb.append(", INT1=").append(INT1);
        sb.append(", INT2=").append(INT2);
        sb.append(", INT3=").append(INT3);
        sb.append(", INT4=").append(INT4);
        sb.append(", INT5=").append(INT5);
        sb.append(", INT6=").append(INT6);
        sb.append(", INT7=").append(INT7);
        sb.append(", INT8=").append(INT8);
        sb.append(", INT9=").append(INT9);
        sb.append(", INT10=").append(INT10);
        sb.append(", DATE1=").append(DATE1);
        sb.append(", DATE2=").append(DATE2);
        sb.append(", DATE3=").append(DATE3);
        sb.append(", DATE4=").append(DATE4);
        sb.append(", DATE5=").append(DATE5);
        sb.append(", DATE6=").append(DATE6);
        sb.append(", DATE7=").append(DATE7);
        sb.append(", DATE8=").append(DATE8);
        sb.append(", DATE9=").append(DATE9);
        sb.append(", DATE10=").append(DATE10);
        sb.append(", FLOAT1=").append(FLOAT1);
        sb.append(", FLOAT2=").append(FLOAT2);
        sb.append(", FLOAT3=").append(FLOAT3);
        sb.append(", FLOAT4=").append(FLOAT4);
        sb.append(", FLOAT5=").append(FLOAT5);
        sb.append(", FLOAT6=").append(FLOAT6);
        sb.append(", FLOAT7=").append(FLOAT7);
        sb.append(", FLOAT8=").append(FLOAT8);
        sb.append(", FLOAT9=").append(FLOAT9);
        sb.append(", FLOAT10=").append(FLOAT10);
        sb.append("]");
        return sb.toString();
    }
}