package com.megalink.study.model.nochange;

public class MemberLinkWithBLOBs extends MemberLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD1
     *
     * @mbggenerated
     */
    private String FIELD1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD2
     *
     * @mbggenerated
     */
    private String FIELD2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD3
     *
     * @mbggenerated
     */
    private String FIELD3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD4
     *
     * @mbggenerated
     */
    private String FIELD4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD5
     *
     * @mbggenerated
     */
    private String FIELD5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD6
     *
     * @mbggenerated
     */
    private String FIELD6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD7
     *
     * @mbggenerated
     */
    private String FIELD7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD8
     *
     * @mbggenerated
     */
    private String FIELD8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD9
     *
     * @mbggenerated
     */
    private String FIELD9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD10
     *
     * @mbggenerated
     */
    private String FIELD10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD11
     *
     * @mbggenerated
     */
    private String FIELD11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD12
     *
     * @mbggenerated
     */
    private String FIELD12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD13
     *
     * @mbggenerated
     */
    private String FIELD13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD14
     *
     * @mbggenerated
     */
    private String FIELD14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD15
     *
     * @mbggenerated
     */
    private String FIELD15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD16
     *
     * @mbggenerated
     */
    private String FIELD16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD17
     *
     * @mbggenerated
     */
    private String FIELD17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD18
     *
     * @mbggenerated
     */
    private String FIELD18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD19
     *
     * @mbggenerated
     */
    private String FIELD19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FIELD20
     *
     * @mbggenerated
     */
    private String FIELD20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD1
     *
     * @return the value of memberlink.FIELD1
     *
     * @mbggenerated
     */
    public String getFIELD1() {
        return FIELD1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD1
     *
     * @param FIELD1 the value for memberlink.FIELD1
     *
     * @mbggenerated
     */
    public void setFIELD1(String FIELD1) {
        this.FIELD1 = FIELD1 == null ? null : FIELD1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD2
     *
     * @return the value of memberlink.FIELD2
     *
     * @mbggenerated
     */
    public String getFIELD2() {
        return FIELD2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD2
     *
     * @param FIELD2 the value for memberlink.FIELD2
     *
     * @mbggenerated
     */
    public void setFIELD2(String FIELD2) {
        this.FIELD2 = FIELD2 == null ? null : FIELD2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD3
     *
     * @return the value of memberlink.FIELD3
     *
     * @mbggenerated
     */
    public String getFIELD3() {
        return FIELD3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD3
     *
     * @param FIELD3 the value for memberlink.FIELD3
     *
     * @mbggenerated
     */
    public void setFIELD3(String FIELD3) {
        this.FIELD3 = FIELD3 == null ? null : FIELD3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD4
     *
     * @return the value of memberlink.FIELD4
     *
     * @mbggenerated
     */
    public String getFIELD4() {
        return FIELD4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD4
     *
     * @param FIELD4 the value for memberlink.FIELD4
     *
     * @mbggenerated
     */
    public void setFIELD4(String FIELD4) {
        this.FIELD4 = FIELD4 == null ? null : FIELD4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD5
     *
     * @return the value of memberlink.FIELD5
     *
     * @mbggenerated
     */
    public String getFIELD5() {
        return FIELD5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD5
     *
     * @param FIELD5 the value for memberlink.FIELD5
     *
     * @mbggenerated
     */
    public void setFIELD5(String FIELD5) {
        this.FIELD5 = FIELD5 == null ? null : FIELD5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD6
     *
     * @return the value of memberlink.FIELD6
     *
     * @mbggenerated
     */
    public String getFIELD6() {
        return FIELD6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD6
     *
     * @param FIELD6 the value for memberlink.FIELD6
     *
     * @mbggenerated
     */
    public void setFIELD6(String FIELD6) {
        this.FIELD6 = FIELD6 == null ? null : FIELD6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD7
     *
     * @return the value of memberlink.FIELD7
     *
     * @mbggenerated
     */
    public String getFIELD7() {
        return FIELD7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD7
     *
     * @param FIELD7 the value for memberlink.FIELD7
     *
     * @mbggenerated
     */
    public void setFIELD7(String FIELD7) {
        this.FIELD7 = FIELD7 == null ? null : FIELD7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD8
     *
     * @return the value of memberlink.FIELD8
     *
     * @mbggenerated
     */
    public String getFIELD8() {
        return FIELD8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD8
     *
     * @param FIELD8 the value for memberlink.FIELD8
     *
     * @mbggenerated
     */
    public void setFIELD8(String FIELD8) {
        this.FIELD8 = FIELD8 == null ? null : FIELD8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD9
     *
     * @return the value of memberlink.FIELD9
     *
     * @mbggenerated
     */
    public String getFIELD9() {
        return FIELD9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD9
     *
     * @param FIELD9 the value for memberlink.FIELD9
     *
     * @mbggenerated
     */
    public void setFIELD9(String FIELD9) {
        this.FIELD9 = FIELD9 == null ? null : FIELD9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD10
     *
     * @return the value of memberlink.FIELD10
     *
     * @mbggenerated
     */
    public String getFIELD10() {
        return FIELD10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD10
     *
     * @param FIELD10 the value for memberlink.FIELD10
     *
     * @mbggenerated
     */
    public void setFIELD10(String FIELD10) {
        this.FIELD10 = FIELD10 == null ? null : FIELD10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD11
     *
     * @return the value of memberlink.FIELD11
     *
     * @mbggenerated
     */
    public String getFIELD11() {
        return FIELD11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD11
     *
     * @param FIELD11 the value for memberlink.FIELD11
     *
     * @mbggenerated
     */
    public void setFIELD11(String FIELD11) {
        this.FIELD11 = FIELD11 == null ? null : FIELD11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD12
     *
     * @return the value of memberlink.FIELD12
     *
     * @mbggenerated
     */
    public String getFIELD12() {
        return FIELD12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD12
     *
     * @param FIELD12 the value for memberlink.FIELD12
     *
     * @mbggenerated
     */
    public void setFIELD12(String FIELD12) {
        this.FIELD12 = FIELD12 == null ? null : FIELD12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD13
     *
     * @return the value of memberlink.FIELD13
     *
     * @mbggenerated
     */
    public String getFIELD13() {
        return FIELD13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD13
     *
     * @param FIELD13 the value for memberlink.FIELD13
     *
     * @mbggenerated
     */
    public void setFIELD13(String FIELD13) {
        this.FIELD13 = FIELD13 == null ? null : FIELD13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD14
     *
     * @return the value of memberlink.FIELD14
     *
     * @mbggenerated
     */
    public String getFIELD14() {
        return FIELD14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD14
     *
     * @param FIELD14 the value for memberlink.FIELD14
     *
     * @mbggenerated
     */
    public void setFIELD14(String FIELD14) {
        this.FIELD14 = FIELD14 == null ? null : FIELD14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD15
     *
     * @return the value of memberlink.FIELD15
     *
     * @mbggenerated
     */
    public String getFIELD15() {
        return FIELD15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD15
     *
     * @param FIELD15 the value for memberlink.FIELD15
     *
     * @mbggenerated
     */
    public void setFIELD15(String FIELD15) {
        this.FIELD15 = FIELD15 == null ? null : FIELD15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD16
     *
     * @return the value of memberlink.FIELD16
     *
     * @mbggenerated
     */
    public String getFIELD16() {
        return FIELD16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD16
     *
     * @param FIELD16 the value for memberlink.FIELD16
     *
     * @mbggenerated
     */
    public void setFIELD16(String FIELD16) {
        this.FIELD16 = FIELD16 == null ? null : FIELD16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD17
     *
     * @return the value of memberlink.FIELD17
     *
     * @mbggenerated
     */
    public String getFIELD17() {
        return FIELD17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD17
     *
     * @param FIELD17 the value for memberlink.FIELD17
     *
     * @mbggenerated
     */
    public void setFIELD17(String FIELD17) {
        this.FIELD17 = FIELD17 == null ? null : FIELD17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD18
     *
     * @return the value of memberlink.FIELD18
     *
     * @mbggenerated
     */
    public String getFIELD18() {
        return FIELD18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD18
     *
     * @param FIELD18 the value for memberlink.FIELD18
     *
     * @mbggenerated
     */
    public void setFIELD18(String FIELD18) {
        this.FIELD18 = FIELD18 == null ? null : FIELD18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD19
     *
     * @return the value of memberlink.FIELD19
     *
     * @mbggenerated
     */
    public String getFIELD19() {
        return FIELD19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD19
     *
     * @param FIELD19 the value for memberlink.FIELD19
     *
     * @mbggenerated
     */
    public void setFIELD19(String FIELD19) {
        this.FIELD19 = FIELD19 == null ? null : FIELD19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FIELD20
     *
     * @return the value of memberlink.FIELD20
     *
     * @mbggenerated
     */
    public String getFIELD20() {
        return FIELD20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FIELD20
     *
     * @param FIELD20 the value for memberlink.FIELD20
     *
     * @mbggenerated
     */
    public void setFIELD20(String FIELD20) {
        this.FIELD20 = FIELD20 == null ? null : FIELD20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", FIELD1=").append(FIELD1);
        sb.append(", FIELD2=").append(FIELD2);
        sb.append(", FIELD3=").append(FIELD3);
        sb.append(", FIELD4=").append(FIELD4);
        sb.append(", FIELD5=").append(FIELD5);
        sb.append(", FIELD6=").append(FIELD6);
        sb.append(", FIELD7=").append(FIELD7);
        sb.append(", FIELD8=").append(FIELD8);
        sb.append(", FIELD9=").append(FIELD9);
        sb.append(", FIELD10=").append(FIELD10);
        sb.append(", FIELD11=").append(FIELD11);
        sb.append(", FIELD12=").append(FIELD12);
        sb.append(", FIELD13=").append(FIELD13);
        sb.append(", FIELD14=").append(FIELD14);
        sb.append(", FIELD15=").append(FIELD15);
        sb.append(", FIELD16=").append(FIELD16);
        sb.append(", FIELD17=").append(FIELD17);
        sb.append(", FIELD18=").append(FIELD18);
        sb.append(", FIELD19=").append(FIELD19);
        sb.append(", FIELD20=").append(FIELD20);
        sb.append("]");
        return sb.toString();
    }
}