package com.megalink.study.model.nochange;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MemberLinkExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public MemberLinkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Long value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Long value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Long value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Long value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Long> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Long> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSIsNull() {
            addCriterion("ROLEACLASS is null");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSIsNotNull() {
            addCriterion("ROLEACLASS is not null");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSEqualTo(String value) {
            addCriterion("ROLEACLASS =", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSNotEqualTo(String value) {
            addCriterion("ROLEACLASS <>", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSGreaterThan(String value) {
            addCriterion("ROLEACLASS >", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEACLASS >=", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSLessThan(String value) {
            addCriterion("ROLEACLASS <", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSLessThanOrEqualTo(String value) {
            addCriterion("ROLEACLASS <=", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSLike(String value) {
            addCriterion("ROLEACLASS like", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSNotLike(String value) {
            addCriterion("ROLEACLASS not like", value, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSIn(List<String> values) {
            addCriterion("ROLEACLASS in", values, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSNotIn(List<String> values) {
            addCriterion("ROLEACLASS not in", values, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSBetween(String value1, String value2) {
            addCriterion("ROLEACLASS between", value1, value2, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEACLASSNotBetween(String value1, String value2) {
            addCriterion("ROLEACLASS not between", value1, value2, "ROLEACLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSIsNull() {
            addCriterion("ROLEBCLASS is null");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSIsNotNull() {
            addCriterion("ROLEBCLASS is not null");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSEqualTo(String value) {
            addCriterion("ROLEBCLASS =", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSNotEqualTo(String value) {
            addCriterion("ROLEBCLASS <>", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSGreaterThan(String value) {
            addCriterion("ROLEBCLASS >", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEBCLASS >=", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSLessThan(String value) {
            addCriterion("ROLEBCLASS <", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSLessThanOrEqualTo(String value) {
            addCriterion("ROLEBCLASS <=", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSLike(String value) {
            addCriterion("ROLEBCLASS like", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSNotLike(String value) {
            addCriterion("ROLEBCLASS not like", value, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSIn(List<String> values) {
            addCriterion("ROLEBCLASS in", values, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSNotIn(List<String> values) {
            addCriterion("ROLEBCLASS not in", values, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSBetween(String value1, String value2) {
            addCriterion("ROLEBCLASS between", value1, value2, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andROLEBCLASSNotBetween(String value1, String value2) {
            addCriterion("ROLEBCLASS not between", value1, value2, "ROLEBCLASS");
            return (Criteria) this;
        }

        public Criteria andINT1IsNull() {
            addCriterion("INT1 is null");
            return (Criteria) this;
        }

        public Criteria andINT1IsNotNull() {
            addCriterion("INT1 is not null");
            return (Criteria) this;
        }

        public Criteria andINT1EqualTo(Integer value) {
            addCriterion("INT1 =", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1NotEqualTo(Integer value) {
            addCriterion("INT1 <>", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1GreaterThan(Integer value) {
            addCriterion("INT1 >", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT1 >=", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1LessThan(Integer value) {
            addCriterion("INT1 <", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1LessThanOrEqualTo(Integer value) {
            addCriterion("INT1 <=", value, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1In(List<Integer> values) {
            addCriterion("INT1 in", values, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1NotIn(List<Integer> values) {
            addCriterion("INT1 not in", values, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1Between(Integer value1, Integer value2) {
            addCriterion("INT1 between", value1, value2, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT1NotBetween(Integer value1, Integer value2) {
            addCriterion("INT1 not between", value1, value2, "INT1");
            return (Criteria) this;
        }

        public Criteria andINT2IsNull() {
            addCriterion("INT2 is null");
            return (Criteria) this;
        }

        public Criteria andINT2IsNotNull() {
            addCriterion("INT2 is not null");
            return (Criteria) this;
        }

        public Criteria andINT2EqualTo(Integer value) {
            addCriterion("INT2 =", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2NotEqualTo(Integer value) {
            addCriterion("INT2 <>", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2GreaterThan(Integer value) {
            addCriterion("INT2 >", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT2 >=", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2LessThan(Integer value) {
            addCriterion("INT2 <", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2LessThanOrEqualTo(Integer value) {
            addCriterion("INT2 <=", value, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2In(List<Integer> values) {
            addCriterion("INT2 in", values, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2NotIn(List<Integer> values) {
            addCriterion("INT2 not in", values, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2Between(Integer value1, Integer value2) {
            addCriterion("INT2 between", value1, value2, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT2NotBetween(Integer value1, Integer value2) {
            addCriterion("INT2 not between", value1, value2, "INT2");
            return (Criteria) this;
        }

        public Criteria andINT3IsNull() {
            addCriterion("INT3 is null");
            return (Criteria) this;
        }

        public Criteria andINT3IsNotNull() {
            addCriterion("INT3 is not null");
            return (Criteria) this;
        }

        public Criteria andINT3EqualTo(Integer value) {
            addCriterion("INT3 =", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3NotEqualTo(Integer value) {
            addCriterion("INT3 <>", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3GreaterThan(Integer value) {
            addCriterion("INT3 >", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT3 >=", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3LessThan(Integer value) {
            addCriterion("INT3 <", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3LessThanOrEqualTo(Integer value) {
            addCriterion("INT3 <=", value, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3In(List<Integer> values) {
            addCriterion("INT3 in", values, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3NotIn(List<Integer> values) {
            addCriterion("INT3 not in", values, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3Between(Integer value1, Integer value2) {
            addCriterion("INT3 between", value1, value2, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT3NotBetween(Integer value1, Integer value2) {
            addCriterion("INT3 not between", value1, value2, "INT3");
            return (Criteria) this;
        }

        public Criteria andINT4IsNull() {
            addCriterion("INT4 is null");
            return (Criteria) this;
        }

        public Criteria andINT4IsNotNull() {
            addCriterion("INT4 is not null");
            return (Criteria) this;
        }

        public Criteria andINT4EqualTo(Integer value) {
            addCriterion("INT4 =", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4NotEqualTo(Integer value) {
            addCriterion("INT4 <>", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4GreaterThan(Integer value) {
            addCriterion("INT4 >", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT4 >=", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4LessThan(Integer value) {
            addCriterion("INT4 <", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4LessThanOrEqualTo(Integer value) {
            addCriterion("INT4 <=", value, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4In(List<Integer> values) {
            addCriterion("INT4 in", values, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4NotIn(List<Integer> values) {
            addCriterion("INT4 not in", values, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4Between(Integer value1, Integer value2) {
            addCriterion("INT4 between", value1, value2, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT4NotBetween(Integer value1, Integer value2) {
            addCriterion("INT4 not between", value1, value2, "INT4");
            return (Criteria) this;
        }

        public Criteria andINT5IsNull() {
            addCriterion("INT5 is null");
            return (Criteria) this;
        }

        public Criteria andINT5IsNotNull() {
            addCriterion("INT5 is not null");
            return (Criteria) this;
        }

        public Criteria andINT5EqualTo(Integer value) {
            addCriterion("INT5 =", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5NotEqualTo(Integer value) {
            addCriterion("INT5 <>", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5GreaterThan(Integer value) {
            addCriterion("INT5 >", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT5 >=", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5LessThan(Integer value) {
            addCriterion("INT5 <", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5LessThanOrEqualTo(Integer value) {
            addCriterion("INT5 <=", value, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5In(List<Integer> values) {
            addCriterion("INT5 in", values, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5NotIn(List<Integer> values) {
            addCriterion("INT5 not in", values, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5Between(Integer value1, Integer value2) {
            addCriterion("INT5 between", value1, value2, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT5NotBetween(Integer value1, Integer value2) {
            addCriterion("INT5 not between", value1, value2, "INT5");
            return (Criteria) this;
        }

        public Criteria andINT6IsNull() {
            addCriterion("INT6 is null");
            return (Criteria) this;
        }

        public Criteria andINT6IsNotNull() {
            addCriterion("INT6 is not null");
            return (Criteria) this;
        }

        public Criteria andINT6EqualTo(Integer value) {
            addCriterion("INT6 =", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6NotEqualTo(Integer value) {
            addCriterion("INT6 <>", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6GreaterThan(Integer value) {
            addCriterion("INT6 >", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT6 >=", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6LessThan(Integer value) {
            addCriterion("INT6 <", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6LessThanOrEqualTo(Integer value) {
            addCriterion("INT6 <=", value, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6In(List<Integer> values) {
            addCriterion("INT6 in", values, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6NotIn(List<Integer> values) {
            addCriterion("INT6 not in", values, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6Between(Integer value1, Integer value2) {
            addCriterion("INT6 between", value1, value2, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT6NotBetween(Integer value1, Integer value2) {
            addCriterion("INT6 not between", value1, value2, "INT6");
            return (Criteria) this;
        }

        public Criteria andINT7IsNull() {
            addCriterion("INT7 is null");
            return (Criteria) this;
        }

        public Criteria andINT7IsNotNull() {
            addCriterion("INT7 is not null");
            return (Criteria) this;
        }

        public Criteria andINT7EqualTo(Integer value) {
            addCriterion("INT7 =", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7NotEqualTo(Integer value) {
            addCriterion("INT7 <>", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7GreaterThan(Integer value) {
            addCriterion("INT7 >", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT7 >=", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7LessThan(Integer value) {
            addCriterion("INT7 <", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7LessThanOrEqualTo(Integer value) {
            addCriterion("INT7 <=", value, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7In(List<Integer> values) {
            addCriterion("INT7 in", values, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7NotIn(List<Integer> values) {
            addCriterion("INT7 not in", values, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7Between(Integer value1, Integer value2) {
            addCriterion("INT7 between", value1, value2, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT7NotBetween(Integer value1, Integer value2) {
            addCriterion("INT7 not between", value1, value2, "INT7");
            return (Criteria) this;
        }

        public Criteria andINT8IsNull() {
            addCriterion("INT8 is null");
            return (Criteria) this;
        }

        public Criteria andINT8IsNotNull() {
            addCriterion("INT8 is not null");
            return (Criteria) this;
        }

        public Criteria andINT8EqualTo(Integer value) {
            addCriterion("INT8 =", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8NotEqualTo(Integer value) {
            addCriterion("INT8 <>", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8GreaterThan(Integer value) {
            addCriterion("INT8 >", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT8 >=", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8LessThan(Integer value) {
            addCriterion("INT8 <", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8LessThanOrEqualTo(Integer value) {
            addCriterion("INT8 <=", value, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8In(List<Integer> values) {
            addCriterion("INT8 in", values, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8NotIn(List<Integer> values) {
            addCriterion("INT8 not in", values, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8Between(Integer value1, Integer value2) {
            addCriterion("INT8 between", value1, value2, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT8NotBetween(Integer value1, Integer value2) {
            addCriterion("INT8 not between", value1, value2, "INT8");
            return (Criteria) this;
        }

        public Criteria andINT9IsNull() {
            addCriterion("INT9 is null");
            return (Criteria) this;
        }

        public Criteria andINT9IsNotNull() {
            addCriterion("INT9 is not null");
            return (Criteria) this;
        }

        public Criteria andINT9EqualTo(Integer value) {
            addCriterion("INT9 =", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9NotEqualTo(Integer value) {
            addCriterion("INT9 <>", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9GreaterThan(Integer value) {
            addCriterion("INT9 >", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT9 >=", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9LessThan(Integer value) {
            addCriterion("INT9 <", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9LessThanOrEqualTo(Integer value) {
            addCriterion("INT9 <=", value, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9In(List<Integer> values) {
            addCriterion("INT9 in", values, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9NotIn(List<Integer> values) {
            addCriterion("INT9 not in", values, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9Between(Integer value1, Integer value2) {
            addCriterion("INT9 between", value1, value2, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT9NotBetween(Integer value1, Integer value2) {
            addCriterion("INT9 not between", value1, value2, "INT9");
            return (Criteria) this;
        }

        public Criteria andINT10IsNull() {
            addCriterion("INT10 is null");
            return (Criteria) this;
        }

        public Criteria andINT10IsNotNull() {
            addCriterion("INT10 is not null");
            return (Criteria) this;
        }

        public Criteria andINT10EqualTo(Integer value) {
            addCriterion("INT10 =", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10NotEqualTo(Integer value) {
            addCriterion("INT10 <>", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10GreaterThan(Integer value) {
            addCriterion("INT10 >", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10GreaterThanOrEqualTo(Integer value) {
            addCriterion("INT10 >=", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10LessThan(Integer value) {
            addCriterion("INT10 <", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10LessThanOrEqualTo(Integer value) {
            addCriterion("INT10 <=", value, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10In(List<Integer> values) {
            addCriterion("INT10 in", values, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10NotIn(List<Integer> values) {
            addCriterion("INT10 not in", values, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10Between(Integer value1, Integer value2) {
            addCriterion("INT10 between", value1, value2, "INT10");
            return (Criteria) this;
        }

        public Criteria andINT10NotBetween(Integer value1, Integer value2) {
            addCriterion("INT10 not between", value1, value2, "INT10");
            return (Criteria) this;
        }

        public Criteria andDATE1IsNull() {
            addCriterion("DATE1 is null");
            return (Criteria) this;
        }

        public Criteria andDATE1IsNotNull() {
            addCriterion("DATE1 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE1EqualTo(Date value) {
            addCriterion("DATE1 =", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1NotEqualTo(Date value) {
            addCriterion("DATE1 <>", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1GreaterThan(Date value) {
            addCriterion("DATE1 >", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE1 >=", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1LessThan(Date value) {
            addCriterion("DATE1 <", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1LessThanOrEqualTo(Date value) {
            addCriterion("DATE1 <=", value, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1In(List<Date> values) {
            addCriterion("DATE1 in", values, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1NotIn(List<Date> values) {
            addCriterion("DATE1 not in", values, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1Between(Date value1, Date value2) {
            addCriterion("DATE1 between", value1, value2, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE1NotBetween(Date value1, Date value2) {
            addCriterion("DATE1 not between", value1, value2, "DATE1");
            return (Criteria) this;
        }

        public Criteria andDATE2IsNull() {
            addCriterion("DATE2 is null");
            return (Criteria) this;
        }

        public Criteria andDATE2IsNotNull() {
            addCriterion("DATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE2EqualTo(Date value) {
            addCriterion("DATE2 =", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2NotEqualTo(Date value) {
            addCriterion("DATE2 <>", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2GreaterThan(Date value) {
            addCriterion("DATE2 >", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE2 >=", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2LessThan(Date value) {
            addCriterion("DATE2 <", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2LessThanOrEqualTo(Date value) {
            addCriterion("DATE2 <=", value, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2In(List<Date> values) {
            addCriterion("DATE2 in", values, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2NotIn(List<Date> values) {
            addCriterion("DATE2 not in", values, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2Between(Date value1, Date value2) {
            addCriterion("DATE2 between", value1, value2, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE2NotBetween(Date value1, Date value2) {
            addCriterion("DATE2 not between", value1, value2, "DATE2");
            return (Criteria) this;
        }

        public Criteria andDATE3IsNull() {
            addCriterion("DATE3 is null");
            return (Criteria) this;
        }

        public Criteria andDATE3IsNotNull() {
            addCriterion("DATE3 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE3EqualTo(Date value) {
            addCriterion("DATE3 =", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3NotEqualTo(Date value) {
            addCriterion("DATE3 <>", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3GreaterThan(Date value) {
            addCriterion("DATE3 >", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE3 >=", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3LessThan(Date value) {
            addCriterion("DATE3 <", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3LessThanOrEqualTo(Date value) {
            addCriterion("DATE3 <=", value, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3In(List<Date> values) {
            addCriterion("DATE3 in", values, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3NotIn(List<Date> values) {
            addCriterion("DATE3 not in", values, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3Between(Date value1, Date value2) {
            addCriterion("DATE3 between", value1, value2, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE3NotBetween(Date value1, Date value2) {
            addCriterion("DATE3 not between", value1, value2, "DATE3");
            return (Criteria) this;
        }

        public Criteria andDATE4IsNull() {
            addCriterion("DATE4 is null");
            return (Criteria) this;
        }

        public Criteria andDATE4IsNotNull() {
            addCriterion("DATE4 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE4EqualTo(Date value) {
            addCriterion("DATE4 =", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4NotEqualTo(Date value) {
            addCriterion("DATE4 <>", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4GreaterThan(Date value) {
            addCriterion("DATE4 >", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE4 >=", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4LessThan(Date value) {
            addCriterion("DATE4 <", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4LessThanOrEqualTo(Date value) {
            addCriterion("DATE4 <=", value, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4In(List<Date> values) {
            addCriterion("DATE4 in", values, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4NotIn(List<Date> values) {
            addCriterion("DATE4 not in", values, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4Between(Date value1, Date value2) {
            addCriterion("DATE4 between", value1, value2, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE4NotBetween(Date value1, Date value2) {
            addCriterion("DATE4 not between", value1, value2, "DATE4");
            return (Criteria) this;
        }

        public Criteria andDATE5IsNull() {
            addCriterion("DATE5 is null");
            return (Criteria) this;
        }

        public Criteria andDATE5IsNotNull() {
            addCriterion("DATE5 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE5EqualTo(Date value) {
            addCriterion("DATE5 =", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5NotEqualTo(Date value) {
            addCriterion("DATE5 <>", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5GreaterThan(Date value) {
            addCriterion("DATE5 >", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE5 >=", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5LessThan(Date value) {
            addCriterion("DATE5 <", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5LessThanOrEqualTo(Date value) {
            addCriterion("DATE5 <=", value, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5In(List<Date> values) {
            addCriterion("DATE5 in", values, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5NotIn(List<Date> values) {
            addCriterion("DATE5 not in", values, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5Between(Date value1, Date value2) {
            addCriterion("DATE5 between", value1, value2, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE5NotBetween(Date value1, Date value2) {
            addCriterion("DATE5 not between", value1, value2, "DATE5");
            return (Criteria) this;
        }

        public Criteria andDATE6IsNull() {
            addCriterion("DATE6 is null");
            return (Criteria) this;
        }

        public Criteria andDATE6IsNotNull() {
            addCriterion("DATE6 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE6EqualTo(Date value) {
            addCriterion("DATE6 =", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6NotEqualTo(Date value) {
            addCriterion("DATE6 <>", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6GreaterThan(Date value) {
            addCriterion("DATE6 >", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE6 >=", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6LessThan(Date value) {
            addCriterion("DATE6 <", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6LessThanOrEqualTo(Date value) {
            addCriterion("DATE6 <=", value, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6In(List<Date> values) {
            addCriterion("DATE6 in", values, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6NotIn(List<Date> values) {
            addCriterion("DATE6 not in", values, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6Between(Date value1, Date value2) {
            addCriterion("DATE6 between", value1, value2, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE6NotBetween(Date value1, Date value2) {
            addCriterion("DATE6 not between", value1, value2, "DATE6");
            return (Criteria) this;
        }

        public Criteria andDATE7IsNull() {
            addCriterion("DATE7 is null");
            return (Criteria) this;
        }

        public Criteria andDATE7IsNotNull() {
            addCriterion("DATE7 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE7EqualTo(Date value) {
            addCriterion("DATE7 =", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7NotEqualTo(Date value) {
            addCriterion("DATE7 <>", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7GreaterThan(Date value) {
            addCriterion("DATE7 >", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE7 >=", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7LessThan(Date value) {
            addCriterion("DATE7 <", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7LessThanOrEqualTo(Date value) {
            addCriterion("DATE7 <=", value, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7In(List<Date> values) {
            addCriterion("DATE7 in", values, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7NotIn(List<Date> values) {
            addCriterion("DATE7 not in", values, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7Between(Date value1, Date value2) {
            addCriterion("DATE7 between", value1, value2, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE7NotBetween(Date value1, Date value2) {
            addCriterion("DATE7 not between", value1, value2, "DATE7");
            return (Criteria) this;
        }

        public Criteria andDATE8IsNull() {
            addCriterion("DATE8 is null");
            return (Criteria) this;
        }

        public Criteria andDATE8IsNotNull() {
            addCriterion("DATE8 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE8EqualTo(Date value) {
            addCriterion("DATE8 =", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8NotEqualTo(Date value) {
            addCriterion("DATE8 <>", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8GreaterThan(Date value) {
            addCriterion("DATE8 >", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE8 >=", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8LessThan(Date value) {
            addCriterion("DATE8 <", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8LessThanOrEqualTo(Date value) {
            addCriterion("DATE8 <=", value, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8In(List<Date> values) {
            addCriterion("DATE8 in", values, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8NotIn(List<Date> values) {
            addCriterion("DATE8 not in", values, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8Between(Date value1, Date value2) {
            addCriterion("DATE8 between", value1, value2, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE8NotBetween(Date value1, Date value2) {
            addCriterion("DATE8 not between", value1, value2, "DATE8");
            return (Criteria) this;
        }

        public Criteria andDATE9IsNull() {
            addCriterion("DATE9 is null");
            return (Criteria) this;
        }

        public Criteria andDATE9IsNotNull() {
            addCriterion("DATE9 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE9EqualTo(Date value) {
            addCriterion("DATE9 =", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9NotEqualTo(Date value) {
            addCriterion("DATE9 <>", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9GreaterThan(Date value) {
            addCriterion("DATE9 >", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE9 >=", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9LessThan(Date value) {
            addCriterion("DATE9 <", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9LessThanOrEqualTo(Date value) {
            addCriterion("DATE9 <=", value, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9In(List<Date> values) {
            addCriterion("DATE9 in", values, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9NotIn(List<Date> values) {
            addCriterion("DATE9 not in", values, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9Between(Date value1, Date value2) {
            addCriterion("DATE9 between", value1, value2, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE9NotBetween(Date value1, Date value2) {
            addCriterion("DATE9 not between", value1, value2, "DATE9");
            return (Criteria) this;
        }

        public Criteria andDATE10IsNull() {
            addCriterion("DATE10 is null");
            return (Criteria) this;
        }

        public Criteria andDATE10IsNotNull() {
            addCriterion("DATE10 is not null");
            return (Criteria) this;
        }

        public Criteria andDATE10EqualTo(Date value) {
            addCriterion("DATE10 =", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10NotEqualTo(Date value) {
            addCriterion("DATE10 <>", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10GreaterThan(Date value) {
            addCriterion("DATE10 >", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10GreaterThanOrEqualTo(Date value) {
            addCriterion("DATE10 >=", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10LessThan(Date value) {
            addCriterion("DATE10 <", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10LessThanOrEqualTo(Date value) {
            addCriterion("DATE10 <=", value, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10In(List<Date> values) {
            addCriterion("DATE10 in", values, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10NotIn(List<Date> values) {
            addCriterion("DATE10 not in", values, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10Between(Date value1, Date value2) {
            addCriterion("DATE10 between", value1, value2, "DATE10");
            return (Criteria) this;
        }

        public Criteria andDATE10NotBetween(Date value1, Date value2) {
            addCriterion("DATE10 not between", value1, value2, "DATE10");
            return (Criteria) this;
        }

        public Criteria andFLOAT1IsNull() {
            addCriterion("FLOAT1 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT1IsNotNull() {
            addCriterion("FLOAT1 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT1EqualTo(Float value) {
            addCriterion("FLOAT1 =", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1NotEqualTo(Float value) {
            addCriterion("FLOAT1 <>", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1GreaterThan(Float value) {
            addCriterion("FLOAT1 >", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT1 >=", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1LessThan(Float value) {
            addCriterion("FLOAT1 <", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT1 <=", value, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1In(List<Float> values) {
            addCriterion("FLOAT1 in", values, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1NotIn(List<Float> values) {
            addCriterion("FLOAT1 not in", values, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1Between(Float value1, Float value2) {
            addCriterion("FLOAT1 between", value1, value2, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT1NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT1 not between", value1, value2, "FLOAT1");
            return (Criteria) this;
        }

        public Criteria andFLOAT2IsNull() {
            addCriterion("FLOAT2 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT2IsNotNull() {
            addCriterion("FLOAT2 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT2EqualTo(Float value) {
            addCriterion("FLOAT2 =", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2NotEqualTo(Float value) {
            addCriterion("FLOAT2 <>", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2GreaterThan(Float value) {
            addCriterion("FLOAT2 >", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT2 >=", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2LessThan(Float value) {
            addCriterion("FLOAT2 <", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT2 <=", value, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2In(List<Float> values) {
            addCriterion("FLOAT2 in", values, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2NotIn(List<Float> values) {
            addCriterion("FLOAT2 not in", values, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2Between(Float value1, Float value2) {
            addCriterion("FLOAT2 between", value1, value2, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT2NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT2 not between", value1, value2, "FLOAT2");
            return (Criteria) this;
        }

        public Criteria andFLOAT3IsNull() {
            addCriterion("FLOAT3 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT3IsNotNull() {
            addCriterion("FLOAT3 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT3EqualTo(Float value) {
            addCriterion("FLOAT3 =", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3NotEqualTo(Float value) {
            addCriterion("FLOAT3 <>", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3GreaterThan(Float value) {
            addCriterion("FLOAT3 >", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT3 >=", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3LessThan(Float value) {
            addCriterion("FLOAT3 <", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT3 <=", value, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3In(List<Float> values) {
            addCriterion("FLOAT3 in", values, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3NotIn(List<Float> values) {
            addCriterion("FLOAT3 not in", values, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3Between(Float value1, Float value2) {
            addCriterion("FLOAT3 between", value1, value2, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT3NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT3 not between", value1, value2, "FLOAT3");
            return (Criteria) this;
        }

        public Criteria andFLOAT4IsNull() {
            addCriterion("FLOAT4 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT4IsNotNull() {
            addCriterion("FLOAT4 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT4EqualTo(Float value) {
            addCriterion("FLOAT4 =", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4NotEqualTo(Float value) {
            addCriterion("FLOAT4 <>", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4GreaterThan(Float value) {
            addCriterion("FLOAT4 >", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT4 >=", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4LessThan(Float value) {
            addCriterion("FLOAT4 <", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT4 <=", value, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4In(List<Float> values) {
            addCriterion("FLOAT4 in", values, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4NotIn(List<Float> values) {
            addCriterion("FLOAT4 not in", values, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4Between(Float value1, Float value2) {
            addCriterion("FLOAT4 between", value1, value2, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT4NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT4 not between", value1, value2, "FLOAT4");
            return (Criteria) this;
        }

        public Criteria andFLOAT5IsNull() {
            addCriterion("FLOAT5 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT5IsNotNull() {
            addCriterion("FLOAT5 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT5EqualTo(Float value) {
            addCriterion("FLOAT5 =", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5NotEqualTo(Float value) {
            addCriterion("FLOAT5 <>", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5GreaterThan(Float value) {
            addCriterion("FLOAT5 >", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT5 >=", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5LessThan(Float value) {
            addCriterion("FLOAT5 <", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT5 <=", value, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5In(List<Float> values) {
            addCriterion("FLOAT5 in", values, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5NotIn(List<Float> values) {
            addCriterion("FLOAT5 not in", values, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5Between(Float value1, Float value2) {
            addCriterion("FLOAT5 between", value1, value2, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT5NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT5 not between", value1, value2, "FLOAT5");
            return (Criteria) this;
        }

        public Criteria andFLOAT6IsNull() {
            addCriterion("FLOAT6 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT6IsNotNull() {
            addCriterion("FLOAT6 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT6EqualTo(Float value) {
            addCriterion("FLOAT6 =", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6NotEqualTo(Float value) {
            addCriterion("FLOAT6 <>", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6GreaterThan(Float value) {
            addCriterion("FLOAT6 >", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT6 >=", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6LessThan(Float value) {
            addCriterion("FLOAT6 <", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT6 <=", value, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6In(List<Float> values) {
            addCriterion("FLOAT6 in", values, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6NotIn(List<Float> values) {
            addCriterion("FLOAT6 not in", values, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6Between(Float value1, Float value2) {
            addCriterion("FLOAT6 between", value1, value2, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT6NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT6 not between", value1, value2, "FLOAT6");
            return (Criteria) this;
        }

        public Criteria andFLOAT7IsNull() {
            addCriterion("FLOAT7 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT7IsNotNull() {
            addCriterion("FLOAT7 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT7EqualTo(Float value) {
            addCriterion("FLOAT7 =", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7NotEqualTo(Float value) {
            addCriterion("FLOAT7 <>", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7GreaterThan(Float value) {
            addCriterion("FLOAT7 >", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT7 >=", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7LessThan(Float value) {
            addCriterion("FLOAT7 <", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT7 <=", value, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7In(List<Float> values) {
            addCriterion("FLOAT7 in", values, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7NotIn(List<Float> values) {
            addCriterion("FLOAT7 not in", values, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7Between(Float value1, Float value2) {
            addCriterion("FLOAT7 between", value1, value2, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT7NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT7 not between", value1, value2, "FLOAT7");
            return (Criteria) this;
        }

        public Criteria andFLOAT8IsNull() {
            addCriterion("FLOAT8 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT8IsNotNull() {
            addCriterion("FLOAT8 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT8EqualTo(Float value) {
            addCriterion("FLOAT8 =", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8NotEqualTo(Float value) {
            addCriterion("FLOAT8 <>", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8GreaterThan(Float value) {
            addCriterion("FLOAT8 >", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT8 >=", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8LessThan(Float value) {
            addCriterion("FLOAT8 <", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT8 <=", value, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8In(List<Float> values) {
            addCriterion("FLOAT8 in", values, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8NotIn(List<Float> values) {
            addCriterion("FLOAT8 not in", values, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8Between(Float value1, Float value2) {
            addCriterion("FLOAT8 between", value1, value2, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT8NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT8 not between", value1, value2, "FLOAT8");
            return (Criteria) this;
        }

        public Criteria andFLOAT9IsNull() {
            addCriterion("FLOAT9 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT9IsNotNull() {
            addCriterion("FLOAT9 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT9EqualTo(Float value) {
            addCriterion("FLOAT9 =", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9NotEqualTo(Float value) {
            addCriterion("FLOAT9 <>", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9GreaterThan(Float value) {
            addCriterion("FLOAT9 >", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT9 >=", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9LessThan(Float value) {
            addCriterion("FLOAT9 <", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT9 <=", value, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9In(List<Float> values) {
            addCriterion("FLOAT9 in", values, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9NotIn(List<Float> values) {
            addCriterion("FLOAT9 not in", values, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9Between(Float value1, Float value2) {
            addCriterion("FLOAT9 between", value1, value2, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT9NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT9 not between", value1, value2, "FLOAT9");
            return (Criteria) this;
        }

        public Criteria andFLOAT10IsNull() {
            addCriterion("FLOAT10 is null");
            return (Criteria) this;
        }

        public Criteria andFLOAT10IsNotNull() {
            addCriterion("FLOAT10 is not null");
            return (Criteria) this;
        }

        public Criteria andFLOAT10EqualTo(Float value) {
            addCriterion("FLOAT10 =", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10NotEqualTo(Float value) {
            addCriterion("FLOAT10 <>", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10GreaterThan(Float value) {
            addCriterion("FLOAT10 >", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10GreaterThanOrEqualTo(Float value) {
            addCriterion("FLOAT10 >=", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10LessThan(Float value) {
            addCriterion("FLOAT10 <", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10LessThanOrEqualTo(Float value) {
            addCriterion("FLOAT10 <=", value, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10In(List<Float> values) {
            addCriterion("FLOAT10 in", values, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10NotIn(List<Float> values) {
            addCriterion("FLOAT10 not in", values, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10Between(Float value1, Float value2) {
            addCriterion("FLOAT10 between", value1, value2, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andFLOAT10NotBetween(Float value1, Float value2) {
            addCriterion("FLOAT10 not between", value1, value2, "FLOAT10");
            return (Criteria) this;
        }

        public Criteria andROLEAIDIsNull() {
            addCriterion("ROLEAID is null");
            return (Criteria) this;
        }

        public Criteria andROLEAIDIsNotNull() {
            addCriterion("ROLEAID is not null");
            return (Criteria) this;
        }

        public Criteria andROLEAIDEqualTo(Float value) {
            addCriterion("ROLEAID =", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDNotEqualTo(Float value) {
            addCriterion("ROLEAID <>", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDGreaterThan(Float value) {
            addCriterion("ROLEAID >", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDGreaterThanOrEqualTo(Float value) {
            addCriterion("ROLEAID >=", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDLessThan(Float value) {
            addCriterion("ROLEAID <", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDLessThanOrEqualTo(Float value) {
            addCriterion("ROLEAID <=", value, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDIn(List<Float> values) {
            addCriterion("ROLEAID in", values, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDNotIn(List<Float> values) {
            addCriterion("ROLEAID not in", values, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDBetween(Float value1, Float value2) {
            addCriterion("ROLEAID between", value1, value2, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEAIDNotBetween(Float value1, Float value2) {
            addCriterion("ROLEAID not between", value1, value2, "ROLEAID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDIsNull() {
            addCriterion("ROLEBID is null");
            return (Criteria) this;
        }

        public Criteria andROLEBIDIsNotNull() {
            addCriterion("ROLEBID is not null");
            return (Criteria) this;
        }

        public Criteria andROLEBIDEqualTo(Float value) {
            addCriterion("ROLEBID =", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDNotEqualTo(Float value) {
            addCriterion("ROLEBID <>", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDGreaterThan(Float value) {
            addCriterion("ROLEBID >", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDGreaterThanOrEqualTo(Float value) {
            addCriterion("ROLEBID >=", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDLessThan(Float value) {
            addCriterion("ROLEBID <", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDLessThanOrEqualTo(Float value) {
            addCriterion("ROLEBID <=", value, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDIn(List<Float> values) {
            addCriterion("ROLEBID in", values, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDNotIn(List<Float> values) {
            addCriterion("ROLEBID not in", values, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDBetween(Float value1, Float value2) {
            addCriterion("ROLEBID between", value1, value2, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andROLEBIDNotBetween(Float value1, Float value2) {
            addCriterion("ROLEBID not between", value1, value2, "ROLEBID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDIsNull() {
            addCriterion("PRINCIPALID is null");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDIsNotNull() {
            addCriterion("PRINCIPALID is not null");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDEqualTo(String value) {
            addCriterion("PRINCIPALID =", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDNotEqualTo(String value) {
            addCriterion("PRINCIPALID <>", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDGreaterThan(String value) {
            addCriterion("PRINCIPALID >", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDGreaterThanOrEqualTo(String value) {
            addCriterion("PRINCIPALID >=", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDLessThan(String value) {
            addCriterion("PRINCIPALID <", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDLessThanOrEqualTo(String value) {
            addCriterion("PRINCIPALID <=", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDLike(String value) {
            addCriterion("PRINCIPALID like", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDNotLike(String value) {
            addCriterion("PRINCIPALID not like", value, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDIn(List<String> values) {
            addCriterion("PRINCIPALID in", values, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDNotIn(List<String> values) {
            addCriterion("PRINCIPALID not in", values, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDBetween(String value1, String value2) {
            addCriterion("PRINCIPALID between", value1, value2, "PRINCIPALID");
            return (Criteria) this;
        }

        public Criteria andPRINCIPALIDNotBetween(String value1, String value2) {
            addCriterion("PRINCIPALID not between", value1, value2, "PRINCIPALID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberlink
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}