package com.megalink.study.model.nochange;

import java.util.Date;

public class MemberLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.ID
     *
     * @mbggenerated
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.ROLEACLASS
     *
     * @mbggenerated
     */
    private String ROLEACLASS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.ROLEBCLASS
     *
     * @mbggenerated
     */
    private String ROLEBCLASS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT1
     *
     * @mbggenerated
     */
    private Integer INT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT2
     *
     * @mbggenerated
     */
    private Integer INT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT3
     *
     * @mbggenerated
     */
    private Integer INT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT4
     *
     * @mbggenerated
     */
    private Integer INT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT5
     *
     * @mbggenerated
     */
    private Integer INT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT6
     *
     * @mbggenerated
     */
    private Integer INT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT7
     *
     * @mbggenerated
     */
    private Integer INT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT8
     *
     * @mbggenerated
     */
    private Integer INT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT9
     *
     * @mbggenerated
     */
    private Integer INT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.INT10
     *
     * @mbggenerated
     */
    private Integer INT10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE1
     *
     * @mbggenerated
     */
    private Date DATE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE2
     *
     * @mbggenerated
     */
    private Date DATE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE3
     *
     * @mbggenerated
     */
    private Date DATE3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE4
     *
     * @mbggenerated
     */
    private Date DATE4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE5
     *
     * @mbggenerated
     */
    private Date DATE5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE6
     *
     * @mbggenerated
     */
    private Date DATE6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE7
     *
     * @mbggenerated
     */
    private Date DATE7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE8
     *
     * @mbggenerated
     */
    private Date DATE8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE9
     *
     * @mbggenerated
     */
    private Date DATE9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.DATE10
     *
     * @mbggenerated
     */
    private Date DATE10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT1
     *
     * @mbggenerated
     */
    private Float FLOAT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT2
     *
     * @mbggenerated
     */
    private Float FLOAT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT3
     *
     * @mbggenerated
     */
    private Float FLOAT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT4
     *
     * @mbggenerated
     */
    private Float FLOAT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT5
     *
     * @mbggenerated
     */
    private Float FLOAT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT6
     *
     * @mbggenerated
     */
    private Float FLOAT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT7
     *
     * @mbggenerated
     */
    private Float FLOAT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT8
     *
     * @mbggenerated
     */
    private Float FLOAT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT9
     *
     * @mbggenerated
     */
    private Float FLOAT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.FLOAT10
     *
     * @mbggenerated
     */
    private Float FLOAT10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.ROLEAID
     *
     * @mbggenerated
     */
    private Float ROLEAID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.ROLEBID
     *
     * @mbggenerated
     */
    private Float ROLEBID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberlink.PRINCIPALID
     *
     * @mbggenerated
     */
    private String PRINCIPALID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.ID
     *
     * @return the value of memberlink.ID
     *
     * @mbggenerated
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.ID
     *
     * @param ID the value for memberlink.ID
     *
     * @mbggenerated
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.ROLEACLASS
     *
     * @return the value of memberlink.ROLEACLASS
     *
     * @mbggenerated
     */
    public String getROLEACLASS() {
        return ROLEACLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.ROLEACLASS
     *
     * @param ROLEACLASS the value for memberlink.ROLEACLASS
     *
     * @mbggenerated
     */
    public void setROLEACLASS(String ROLEACLASS) {
        this.ROLEACLASS = ROLEACLASS == null ? null : ROLEACLASS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.ROLEBCLASS
     *
     * @return the value of memberlink.ROLEBCLASS
     *
     * @mbggenerated
     */
    public String getROLEBCLASS() {
        return ROLEBCLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.ROLEBCLASS
     *
     * @param ROLEBCLASS the value for memberlink.ROLEBCLASS
     *
     * @mbggenerated
     */
    public void setROLEBCLASS(String ROLEBCLASS) {
        this.ROLEBCLASS = ROLEBCLASS == null ? null : ROLEBCLASS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT1
     *
     * @return the value of memberlink.INT1
     *
     * @mbggenerated
     */
    public Integer getINT1() {
        return INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT1
     *
     * @param INT1 the value for memberlink.INT1
     *
     * @mbggenerated
     */
    public void setINT1(Integer INT1) {
        this.INT1 = INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT2
     *
     * @return the value of memberlink.INT2
     *
     * @mbggenerated
     */
    public Integer getINT2() {
        return INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT2
     *
     * @param INT2 the value for memberlink.INT2
     *
     * @mbggenerated
     */
    public void setINT2(Integer INT2) {
        this.INT2 = INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT3
     *
     * @return the value of memberlink.INT3
     *
     * @mbggenerated
     */
    public Integer getINT3() {
        return INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT3
     *
     * @param INT3 the value for memberlink.INT3
     *
     * @mbggenerated
     */
    public void setINT3(Integer INT3) {
        this.INT3 = INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT4
     *
     * @return the value of memberlink.INT4
     *
     * @mbggenerated
     */
    public Integer getINT4() {
        return INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT4
     *
     * @param INT4 the value for memberlink.INT4
     *
     * @mbggenerated
     */
    public void setINT4(Integer INT4) {
        this.INT4 = INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT5
     *
     * @return the value of memberlink.INT5
     *
     * @mbggenerated
     */
    public Integer getINT5() {
        return INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT5
     *
     * @param INT5 the value for memberlink.INT5
     *
     * @mbggenerated
     */
    public void setINT5(Integer INT5) {
        this.INT5 = INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT6
     *
     * @return the value of memberlink.INT6
     *
     * @mbggenerated
     */
    public Integer getINT6() {
        return INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT6
     *
     * @param INT6 the value for memberlink.INT6
     *
     * @mbggenerated
     */
    public void setINT6(Integer INT6) {
        this.INT6 = INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT7
     *
     * @return the value of memberlink.INT7
     *
     * @mbggenerated
     */
    public Integer getINT7() {
        return INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT7
     *
     * @param INT7 the value for memberlink.INT7
     *
     * @mbggenerated
     */
    public void setINT7(Integer INT7) {
        this.INT7 = INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT8
     *
     * @return the value of memberlink.INT8
     *
     * @mbggenerated
     */
    public Integer getINT8() {
        return INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT8
     *
     * @param INT8 the value for memberlink.INT8
     *
     * @mbggenerated
     */
    public void setINT8(Integer INT8) {
        this.INT8 = INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT9
     *
     * @return the value of memberlink.INT9
     *
     * @mbggenerated
     */
    public Integer getINT9() {
        return INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT9
     *
     * @param INT9 the value for memberlink.INT9
     *
     * @mbggenerated
     */
    public void setINT9(Integer INT9) {
        this.INT9 = INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.INT10
     *
     * @return the value of memberlink.INT10
     *
     * @mbggenerated
     */
    public Integer getINT10() {
        return INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.INT10
     *
     * @param INT10 the value for memberlink.INT10
     *
     * @mbggenerated
     */
    public void setINT10(Integer INT10) {
        this.INT10 = INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE1
     *
     * @return the value of memberlink.DATE1
     *
     * @mbggenerated
     */
    public Date getDATE1() {
        return DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE1
     *
     * @param DATE1 the value for memberlink.DATE1
     *
     * @mbggenerated
     */
    public void setDATE1(Date DATE1) {
        this.DATE1 = DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE2
     *
     * @return the value of memberlink.DATE2
     *
     * @mbggenerated
     */
    public Date getDATE2() {
        return DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE2
     *
     * @param DATE2 the value for memberlink.DATE2
     *
     * @mbggenerated
     */
    public void setDATE2(Date DATE2) {
        this.DATE2 = DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE3
     *
     * @return the value of memberlink.DATE3
     *
     * @mbggenerated
     */
    public Date getDATE3() {
        return DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE3
     *
     * @param DATE3 the value for memberlink.DATE3
     *
     * @mbggenerated
     */
    public void setDATE3(Date DATE3) {
        this.DATE3 = DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE4
     *
     * @return the value of memberlink.DATE4
     *
     * @mbggenerated
     */
    public Date getDATE4() {
        return DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE4
     *
     * @param DATE4 the value for memberlink.DATE4
     *
     * @mbggenerated
     */
    public void setDATE4(Date DATE4) {
        this.DATE4 = DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE5
     *
     * @return the value of memberlink.DATE5
     *
     * @mbggenerated
     */
    public Date getDATE5() {
        return DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE5
     *
     * @param DATE5 the value for memberlink.DATE5
     *
     * @mbggenerated
     */
    public void setDATE5(Date DATE5) {
        this.DATE5 = DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE6
     *
     * @return the value of memberlink.DATE6
     *
     * @mbggenerated
     */
    public Date getDATE6() {
        return DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE6
     *
     * @param DATE6 the value for memberlink.DATE6
     *
     * @mbggenerated
     */
    public void setDATE6(Date DATE6) {
        this.DATE6 = DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE7
     *
     * @return the value of memberlink.DATE7
     *
     * @mbggenerated
     */
    public Date getDATE7() {
        return DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE7
     *
     * @param DATE7 the value for memberlink.DATE7
     *
     * @mbggenerated
     */
    public void setDATE7(Date DATE7) {
        this.DATE7 = DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE8
     *
     * @return the value of memberlink.DATE8
     *
     * @mbggenerated
     */
    public Date getDATE8() {
        return DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE8
     *
     * @param DATE8 the value for memberlink.DATE8
     *
     * @mbggenerated
     */
    public void setDATE8(Date DATE8) {
        this.DATE8 = DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE9
     *
     * @return the value of memberlink.DATE9
     *
     * @mbggenerated
     */
    public Date getDATE9() {
        return DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE9
     *
     * @param DATE9 the value for memberlink.DATE9
     *
     * @mbggenerated
     */
    public void setDATE9(Date DATE9) {
        this.DATE9 = DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.DATE10
     *
     * @return the value of memberlink.DATE10
     *
     * @mbggenerated
     */
    public Date getDATE10() {
        return DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.DATE10
     *
     * @param DATE10 the value for memberlink.DATE10
     *
     * @mbggenerated
     */
    public void setDATE10(Date DATE10) {
        this.DATE10 = DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT1
     *
     * @return the value of memberlink.FLOAT1
     *
     * @mbggenerated
     */
    public Float getFLOAT1() {
        return FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT1
     *
     * @param FLOAT1 the value for memberlink.FLOAT1
     *
     * @mbggenerated
     */
    public void setFLOAT1(Float FLOAT1) {
        this.FLOAT1 = FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT2
     *
     * @return the value of memberlink.FLOAT2
     *
     * @mbggenerated
     */
    public Float getFLOAT2() {
        return FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT2
     *
     * @param FLOAT2 the value for memberlink.FLOAT2
     *
     * @mbggenerated
     */
    public void setFLOAT2(Float FLOAT2) {
        this.FLOAT2 = FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT3
     *
     * @return the value of memberlink.FLOAT3
     *
     * @mbggenerated
     */
    public Float getFLOAT3() {
        return FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT3
     *
     * @param FLOAT3 the value for memberlink.FLOAT3
     *
     * @mbggenerated
     */
    public void setFLOAT3(Float FLOAT3) {
        this.FLOAT3 = FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT4
     *
     * @return the value of memberlink.FLOAT4
     *
     * @mbggenerated
     */
    public Float getFLOAT4() {
        return FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT4
     *
     * @param FLOAT4 the value for memberlink.FLOAT4
     *
     * @mbggenerated
     */
    public void setFLOAT4(Float FLOAT4) {
        this.FLOAT4 = FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT5
     *
     * @return the value of memberlink.FLOAT5
     *
     * @mbggenerated
     */
    public Float getFLOAT5() {
        return FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT5
     *
     * @param FLOAT5 the value for memberlink.FLOAT5
     *
     * @mbggenerated
     */
    public void setFLOAT5(Float FLOAT5) {
        this.FLOAT5 = FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT6
     *
     * @return the value of memberlink.FLOAT6
     *
     * @mbggenerated
     */
    public Float getFLOAT6() {
        return FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT6
     *
     * @param FLOAT6 the value for memberlink.FLOAT6
     *
     * @mbggenerated
     */
    public void setFLOAT6(Float FLOAT6) {
        this.FLOAT6 = FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT7
     *
     * @return the value of memberlink.FLOAT7
     *
     * @mbggenerated
     */
    public Float getFLOAT7() {
        return FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT7
     *
     * @param FLOAT7 the value for memberlink.FLOAT7
     *
     * @mbggenerated
     */
    public void setFLOAT7(Float FLOAT7) {
        this.FLOAT7 = FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT8
     *
     * @return the value of memberlink.FLOAT8
     *
     * @mbggenerated
     */
    public Float getFLOAT8() {
        return FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT8
     *
     * @param FLOAT8 the value for memberlink.FLOAT8
     *
     * @mbggenerated
     */
    public void setFLOAT8(Float FLOAT8) {
        this.FLOAT8 = FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT9
     *
     * @return the value of memberlink.FLOAT9
     *
     * @mbggenerated
     */
    public Float getFLOAT9() {
        return FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT9
     *
     * @param FLOAT9 the value for memberlink.FLOAT9
     *
     * @mbggenerated
     */
    public void setFLOAT9(Float FLOAT9) {
        this.FLOAT9 = FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.FLOAT10
     *
     * @return the value of memberlink.FLOAT10
     *
     * @mbggenerated
     */
    public Float getFLOAT10() {
        return FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.FLOAT10
     *
     * @param FLOAT10 the value for memberlink.FLOAT10
     *
     * @mbggenerated
     */
    public void setFLOAT10(Float FLOAT10) {
        this.FLOAT10 = FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.ROLEAID
     *
     * @return the value of memberlink.ROLEAID
     *
     * @mbggenerated
     */
    public Float getROLEAID() {
        return ROLEAID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.ROLEAID
     *
     * @param ROLEAID the value for memberlink.ROLEAID
     *
     * @mbggenerated
     */
    public void setROLEAID(Float ROLEAID) {
        this.ROLEAID = ROLEAID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.ROLEBID
     *
     * @return the value of memberlink.ROLEBID
     *
     * @mbggenerated
     */
    public Float getROLEBID() {
        return ROLEBID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.ROLEBID
     *
     * @param ROLEBID the value for memberlink.ROLEBID
     *
     * @mbggenerated
     */
    public void setROLEBID(Float ROLEBID) {
        this.ROLEBID = ROLEBID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberlink.PRINCIPALID
     *
     * @return the value of memberlink.PRINCIPALID
     *
     * @mbggenerated
     */
    public String getPRINCIPALID() {
        return PRINCIPALID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberlink.PRINCIPALID
     *
     * @param PRINCIPALID the value for memberlink.PRINCIPALID
     *
     * @mbggenerated
     */
    public void setPRINCIPALID(String PRINCIPALID) {
        this.PRINCIPALID = PRINCIPALID == null ? null : PRINCIPALID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberlink
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(ID);
        sb.append(", ROLEACLASS=").append(ROLEACLASS);
        sb.append(", ROLEBCLASS=").append(ROLEBCLASS);
        sb.append(", INT1=").append(INT1);
        sb.append(", INT2=").append(INT2);
        sb.append(", INT3=").append(INT3);
        sb.append(", INT4=").append(INT4);
        sb.append(", INT5=").append(INT5);
        sb.append(", INT6=").append(INT6);
        sb.append(", INT7=").append(INT7);
        sb.append(", INT8=").append(INT8);
        sb.append(", INT9=").append(INT9);
        sb.append(", INT10=").append(INT10);
        sb.append(", DATE1=").append(DATE1);
        sb.append(", DATE2=").append(DATE2);
        sb.append(", DATE3=").append(DATE3);
        sb.append(", DATE4=").append(DATE4);
        sb.append(", DATE5=").append(DATE5);
        sb.append(", DATE6=").append(DATE6);
        sb.append(", DATE7=").append(DATE7);
        sb.append(", DATE8=").append(DATE8);
        sb.append(", DATE9=").append(DATE9);
        sb.append(", DATE10=").append(DATE10);
        sb.append(", FLOAT1=").append(FLOAT1);
        sb.append(", FLOAT2=").append(FLOAT2);
        sb.append(", FLOAT3=").append(FLOAT3);
        sb.append(", FLOAT4=").append(FLOAT4);
        sb.append(", FLOAT5=").append(FLOAT5);
        sb.append(", FLOAT6=").append(FLOAT6);
        sb.append(", FLOAT7=").append(FLOAT7);
        sb.append(", FLOAT8=").append(FLOAT8);
        sb.append(", FLOAT9=").append(FLOAT9);
        sb.append(", FLOAT10=").append(FLOAT10);
        sb.append(", ROLEAID=").append(ROLEAID);
        sb.append(", ROLEBID=").append(ROLEBID);
        sb.append(", PRINCIPALID=").append(PRINCIPALID);
        sb.append("]");
        return sb.toString();
    }
}