package com.megalink.study.model.nochange;

import java.util.Date;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    private Long PERMISSION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.DOMAIN_ID
     *
     * @mbggenerated
     */
    private String DOMAIN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.SOFTTYPE
     *
     * @mbggenerated
     */
    private String SOFTTYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.STATUS
     *
     * @mbggenerated
     */
    private String STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.READ_PERMISSION
     *
     * @mbggenerated
     */
    private String READ_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.WRITE_PERMISSION
     *
     * @mbggenerated
     */
    private String WRITE_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.DELETE_PERMISSION
     *
     * @mbggenerated
     */
    private String DELETE_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.ADD_PERMISSION
     *
     * @mbggenerated
     */
    private String ADD_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.ALL_PERMISSION
     *
     * @mbggenerated
     */
    private String ALL_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PRINCIPALID
     *
     * @mbggenerated
     */
    private String PRINCIPALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.CONTAINER_ID
     *
     * @mbggenerated
     */
    private String CONTAINER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.MAG_PERMISSION
     *
     * @mbggenerated
     */
    private String MAG_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.USERID
     *
     * @mbggenerated
     */
    private String USERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.TYPE
     *
     * @mbggenerated
     */
    private String TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.DOWNLOAD_PERMISSION
     *
     * @mbggenerated
     */
    private String DOWNLOAD_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PRINT_PERMISSION
     *
     * @mbggenerated
     */
    private String PRINT_PERMISSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.MODIFIED
     *
     * @mbggenerated
     */
    private Date MODIFIED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.CREATED
     *
     * @mbggenerated
     */
    private Date CREATED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.MODIFIERID
     *
     * @mbggenerated
     */
    private String MODIFIERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.CREATERID
     *
     * @mbggenerated
     */
    private String CREATERID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_ID
     *
     * @return the value of permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    public Long getPERMISSION_ID() {
        return PERMISSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_ID
     *
     * @param PERMISSION_ID the value for permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setPERMISSION_ID(Long PERMISSION_ID) {
        this.PERMISSION_ID = PERMISSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.DOMAIN_ID
     *
     * @return the value of permission.DOMAIN_ID
     *
     * @mbggenerated
     */
    public String getDOMAIN_ID() {
        return DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.DOMAIN_ID
     *
     * @param DOMAIN_ID the value for permission.DOMAIN_ID
     *
     * @mbggenerated
     */
    public void setDOMAIN_ID(String DOMAIN_ID) {
        this.DOMAIN_ID = DOMAIN_ID == null ? null : DOMAIN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.SOFTTYPE
     *
     * @return the value of permission.SOFTTYPE
     *
     * @mbggenerated
     */
    public String getSOFTTYPE() {
        return SOFTTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.SOFTTYPE
     *
     * @param SOFTTYPE the value for permission.SOFTTYPE
     *
     * @mbggenerated
     */
    public void setSOFTTYPE(String SOFTTYPE) {
        this.SOFTTYPE = SOFTTYPE == null ? null : SOFTTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.STATUS
     *
     * @return the value of permission.STATUS
     *
     * @mbggenerated
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.STATUS
     *
     * @param STATUS the value for permission.STATUS
     *
     * @mbggenerated
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.READ_PERMISSION
     *
     * @return the value of permission.READ_PERMISSION
     *
     * @mbggenerated
     */
    public String getREAD_PERMISSION() {
        return READ_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.READ_PERMISSION
     *
     * @param READ_PERMISSION the value for permission.READ_PERMISSION
     *
     * @mbggenerated
     */
    public void setREAD_PERMISSION(String READ_PERMISSION) {
        this.READ_PERMISSION = READ_PERMISSION == null ? null : READ_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.WRITE_PERMISSION
     *
     * @return the value of permission.WRITE_PERMISSION
     *
     * @mbggenerated
     */
    public String getWRITE_PERMISSION() {
        return WRITE_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.WRITE_PERMISSION
     *
     * @param WRITE_PERMISSION the value for permission.WRITE_PERMISSION
     *
     * @mbggenerated
     */
    public void setWRITE_PERMISSION(String WRITE_PERMISSION) {
        this.WRITE_PERMISSION = WRITE_PERMISSION == null ? null : WRITE_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.DELETE_PERMISSION
     *
     * @return the value of permission.DELETE_PERMISSION
     *
     * @mbggenerated
     */
    public String getDELETE_PERMISSION() {
        return DELETE_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.DELETE_PERMISSION
     *
     * @param DELETE_PERMISSION the value for permission.DELETE_PERMISSION
     *
     * @mbggenerated
     */
    public void setDELETE_PERMISSION(String DELETE_PERMISSION) {
        this.DELETE_PERMISSION = DELETE_PERMISSION == null ? null : DELETE_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.ADD_PERMISSION
     *
     * @return the value of permission.ADD_PERMISSION
     *
     * @mbggenerated
     */
    public String getADD_PERMISSION() {
        return ADD_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.ADD_PERMISSION
     *
     * @param ADD_PERMISSION the value for permission.ADD_PERMISSION
     *
     * @mbggenerated
     */
    public void setADD_PERMISSION(String ADD_PERMISSION) {
        this.ADD_PERMISSION = ADD_PERMISSION == null ? null : ADD_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.ALL_PERMISSION
     *
     * @return the value of permission.ALL_PERMISSION
     *
     * @mbggenerated
     */
    public String getALL_PERMISSION() {
        return ALL_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.ALL_PERMISSION
     *
     * @param ALL_PERMISSION the value for permission.ALL_PERMISSION
     *
     * @mbggenerated
     */
    public void setALL_PERMISSION(String ALL_PERMISSION) {
        this.ALL_PERMISSION = ALL_PERMISSION == null ? null : ALL_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PRINCIPALID
     *
     * @return the value of permission.PRINCIPALID
     *
     * @mbggenerated
     */
    public String getPRINCIPALID() {
        return PRINCIPALID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PRINCIPALID
     *
     * @param PRINCIPALID the value for permission.PRINCIPALID
     *
     * @mbggenerated
     */
    public void setPRINCIPALID(String PRINCIPALID) {
        this.PRINCIPALID = PRINCIPALID == null ? null : PRINCIPALID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.CONTAINER_ID
     *
     * @return the value of permission.CONTAINER_ID
     *
     * @mbggenerated
     */
    public String getCONTAINER_ID() {
        return CONTAINER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.CONTAINER_ID
     *
     * @param CONTAINER_ID the value for permission.CONTAINER_ID
     *
     * @mbggenerated
     */
    public void setCONTAINER_ID(String CONTAINER_ID) {
        this.CONTAINER_ID = CONTAINER_ID == null ? null : CONTAINER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.MAG_PERMISSION
     *
     * @return the value of permission.MAG_PERMISSION
     *
     * @mbggenerated
     */
    public String getMAG_PERMISSION() {
        return MAG_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.MAG_PERMISSION
     *
     * @param MAG_PERMISSION the value for permission.MAG_PERMISSION
     *
     * @mbggenerated
     */
    public void setMAG_PERMISSION(String MAG_PERMISSION) {
        this.MAG_PERMISSION = MAG_PERMISSION == null ? null : MAG_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.USERID
     *
     * @return the value of permission.USERID
     *
     * @mbggenerated
     */
    public String getUSERID() {
        return USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.USERID
     *
     * @param USERID the value for permission.USERID
     *
     * @mbggenerated
     */
    public void setUSERID(String USERID) {
        this.USERID = USERID == null ? null : USERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.TYPE
     *
     * @return the value of permission.TYPE
     *
     * @mbggenerated
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.TYPE
     *
     * @param TYPE the value for permission.TYPE
     *
     * @mbggenerated
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.DOWNLOAD_PERMISSION
     *
     * @return the value of permission.DOWNLOAD_PERMISSION
     *
     * @mbggenerated
     */
    public String getDOWNLOAD_PERMISSION() {
        return DOWNLOAD_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.DOWNLOAD_PERMISSION
     *
     * @param DOWNLOAD_PERMISSION the value for permission.DOWNLOAD_PERMISSION
     *
     * @mbggenerated
     */
    public void setDOWNLOAD_PERMISSION(String DOWNLOAD_PERMISSION) {
        this.DOWNLOAD_PERMISSION = DOWNLOAD_PERMISSION == null ? null : DOWNLOAD_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PRINT_PERMISSION
     *
     * @return the value of permission.PRINT_PERMISSION
     *
     * @mbggenerated
     */
    public String getPRINT_PERMISSION() {
        return PRINT_PERMISSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PRINT_PERMISSION
     *
     * @param PRINT_PERMISSION the value for permission.PRINT_PERMISSION
     *
     * @mbggenerated
     */
    public void setPRINT_PERMISSION(String PRINT_PERMISSION) {
        this.PRINT_PERMISSION = PRINT_PERMISSION == null ? null : PRINT_PERMISSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.MODIFIED
     *
     * @return the value of permission.MODIFIED
     *
     * @mbggenerated
     */
    public Date getMODIFIED() {
        return MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.MODIFIED
     *
     * @param MODIFIED the value for permission.MODIFIED
     *
     * @mbggenerated
     */
    public void setMODIFIED(Date MODIFIED) {
        this.MODIFIED = MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.CREATED
     *
     * @return the value of permission.CREATED
     *
     * @mbggenerated
     */
    public Date getCREATED() {
        return CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.CREATED
     *
     * @param CREATED the value for permission.CREATED
     *
     * @mbggenerated
     */
    public void setCREATED(Date CREATED) {
        this.CREATED = CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.MODIFIERID
     *
     * @return the value of permission.MODIFIERID
     *
     * @mbggenerated
     */
    public String getMODIFIERID() {
        return MODIFIERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.MODIFIERID
     *
     * @param MODIFIERID the value for permission.MODIFIERID
     *
     * @mbggenerated
     */
    public void setMODIFIERID(String MODIFIERID) {
        this.MODIFIERID = MODIFIERID == null ? null : MODIFIERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.CREATERID
     *
     * @return the value of permission.CREATERID
     *
     * @mbggenerated
     */
    public String getCREATERID() {
        return CREATERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.CREATERID
     *
     * @param CREATERID the value for permission.CREATERID
     *
     * @mbggenerated
     */
    public void setCREATERID(String CREATERID) {
        this.CREATERID = CREATERID == null ? null : CREATERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", PERMISSION_ID=").append(PERMISSION_ID);
        sb.append(", DOMAIN_ID=").append(DOMAIN_ID);
        sb.append(", SOFTTYPE=").append(SOFTTYPE);
        sb.append(", STATUS=").append(STATUS);
        sb.append(", READ_PERMISSION=").append(READ_PERMISSION);
        sb.append(", WRITE_PERMISSION=").append(WRITE_PERMISSION);
        sb.append(", DELETE_PERMISSION=").append(DELETE_PERMISSION);
        sb.append(", ADD_PERMISSION=").append(ADD_PERMISSION);
        sb.append(", ALL_PERMISSION=").append(ALL_PERMISSION);
        sb.append(", PRINCIPALID=").append(PRINCIPALID);
        sb.append(", CONTAINER_ID=").append(CONTAINER_ID);
        sb.append(", MAG_PERMISSION=").append(MAG_PERMISSION);
        sb.append(", USERID=").append(USERID);
        sb.append(", TYPE=").append(TYPE);
        sb.append(", DOWNLOAD_PERMISSION=").append(DOWNLOAD_PERMISSION);
        sb.append(", PRINT_PERMISSION=").append(PRINT_PERMISSION);
        sb.append(", MODIFIED=").append(MODIFIED);
        sb.append(", CREATED=").append(CREATED);
        sb.append(", MODIFIERID=").append(MODIFIERID);
        sb.append(", CREATERID=").append(CREATERID);
        sb.append("]");
        return sb.toString();
    }
}