package com.megalink.study.model.nochange;

import java.util.Date;

public class Wfdefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.ID
     *
     * @mbggenerated
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.NAME
     *
     * @mbggenerated
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.VERSION
     *
     * @mbggenerated
     */
    private String VERSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.CREATED
     *
     * @mbggenerated
     */
    private Date CREATED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.TITLE
     *
     * @mbggenerated
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.MODIFIED
     *
     * @mbggenerated
     */
    private Date MODIFIED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.STATUS
     *
     * @mbggenerated
     */
    private String STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.ISLATEST
     *
     * @mbggenerated
     */
    private Long ISLATEST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT1
     *
     * @mbggenerated
     */
    private Integer INT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT2
     *
     * @mbggenerated
     */
    private Integer INT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT3
     *
     * @mbggenerated
     */
    private Integer INT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT4
     *
     * @mbggenerated
     */
    private Integer INT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT5
     *
     * @mbggenerated
     */
    private Integer INT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT6
     *
     * @mbggenerated
     */
    private Integer INT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT7
     *
     * @mbggenerated
     */
    private Integer INT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT8
     *
     * @mbggenerated
     */
    private Integer INT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT9
     *
     * @mbggenerated
     */
    private Integer INT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.INT10
     *
     * @mbggenerated
     */
    private Integer INT10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE1
     *
     * @mbggenerated
     */
    private Date DATE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE2
     *
     * @mbggenerated
     */
    private Date DATE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE3
     *
     * @mbggenerated
     */
    private Date DATE3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE4
     *
     * @mbggenerated
     */
    private Date DATE4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE5
     *
     * @mbggenerated
     */
    private Date DATE5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE6
     *
     * @mbggenerated
     */
    private Date DATE6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE7
     *
     * @mbggenerated
     */
    private Date DATE7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE8
     *
     * @mbggenerated
     */
    private Date DATE8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE9
     *
     * @mbggenerated
     */
    private Date DATE9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DATE10
     *
     * @mbggenerated
     */
    private Date DATE10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT1
     *
     * @mbggenerated
     */
    private Float FLOAT1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT2
     *
     * @mbggenerated
     */
    private Float FLOAT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT3
     *
     * @mbggenerated
     */
    private Float FLOAT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT4
     *
     * @mbggenerated
     */
    private Float FLOAT4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT5
     *
     * @mbggenerated
     */
    private Float FLOAT5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT6
     *
     * @mbggenerated
     */
    private Float FLOAT6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT7
     *
     * @mbggenerated
     */
    private Float FLOAT7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT8
     *
     * @mbggenerated
     */
    private Float FLOAT8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT9
     *
     * @mbggenerated
     */
    private Float FLOAT9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.FLOAT10
     *
     * @mbggenerated
     */
    private Float FLOAT10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfdefine.DOMAIN_ID
     *
     * @mbggenerated
     */
    private Long DOMAIN_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.ID
     *
     * @return the value of wfdefine.ID
     *
     * @mbggenerated
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.ID
     *
     * @param ID the value for wfdefine.ID
     *
     * @mbggenerated
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.NAME
     *
     * @return the value of wfdefine.NAME
     *
     * @mbggenerated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.NAME
     *
     * @param NAME the value for wfdefine.NAME
     *
     * @mbggenerated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.VERSION
     *
     * @return the value of wfdefine.VERSION
     *
     * @mbggenerated
     */
    public String getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.VERSION
     *
     * @param VERSION the value for wfdefine.VERSION
     *
     * @mbggenerated
     */
    public void setVERSION(String VERSION) {
        this.VERSION = VERSION == null ? null : VERSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.CREATED
     *
     * @return the value of wfdefine.CREATED
     *
     * @mbggenerated
     */
    public Date getCREATED() {
        return CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.CREATED
     *
     * @param CREATED the value for wfdefine.CREATED
     *
     * @mbggenerated
     */
    public void setCREATED(Date CREATED) {
        this.CREATED = CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.TITLE
     *
     * @return the value of wfdefine.TITLE
     *
     * @mbggenerated
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.TITLE
     *
     * @param TITLE the value for wfdefine.TITLE
     *
     * @mbggenerated
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.MODIFIED
     *
     * @return the value of wfdefine.MODIFIED
     *
     * @mbggenerated
     */
    public Date getMODIFIED() {
        return MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.MODIFIED
     *
     * @param MODIFIED the value for wfdefine.MODIFIED
     *
     * @mbggenerated
     */
    public void setMODIFIED(Date MODIFIED) {
        this.MODIFIED = MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.STATUS
     *
     * @return the value of wfdefine.STATUS
     *
     * @mbggenerated
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.STATUS
     *
     * @param STATUS the value for wfdefine.STATUS
     *
     * @mbggenerated
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.ISLATEST
     *
     * @return the value of wfdefine.ISLATEST
     *
     * @mbggenerated
     */
    public Long getISLATEST() {
        return ISLATEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.ISLATEST
     *
     * @param ISLATEST the value for wfdefine.ISLATEST
     *
     * @mbggenerated
     */
    public void setISLATEST(Long ISLATEST) {
        this.ISLATEST = ISLATEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT1
     *
     * @return the value of wfdefine.INT1
     *
     * @mbggenerated
     */
    public Integer getINT1() {
        return INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT1
     *
     * @param INT1 the value for wfdefine.INT1
     *
     * @mbggenerated
     */
    public void setINT1(Integer INT1) {
        this.INT1 = INT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT2
     *
     * @return the value of wfdefine.INT2
     *
     * @mbggenerated
     */
    public Integer getINT2() {
        return INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT2
     *
     * @param INT2 the value for wfdefine.INT2
     *
     * @mbggenerated
     */
    public void setINT2(Integer INT2) {
        this.INT2 = INT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT3
     *
     * @return the value of wfdefine.INT3
     *
     * @mbggenerated
     */
    public Integer getINT3() {
        return INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT3
     *
     * @param INT3 the value for wfdefine.INT3
     *
     * @mbggenerated
     */
    public void setINT3(Integer INT3) {
        this.INT3 = INT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT4
     *
     * @return the value of wfdefine.INT4
     *
     * @mbggenerated
     */
    public Integer getINT4() {
        return INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT4
     *
     * @param INT4 the value for wfdefine.INT4
     *
     * @mbggenerated
     */
    public void setINT4(Integer INT4) {
        this.INT4 = INT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT5
     *
     * @return the value of wfdefine.INT5
     *
     * @mbggenerated
     */
    public Integer getINT5() {
        return INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT5
     *
     * @param INT5 the value for wfdefine.INT5
     *
     * @mbggenerated
     */
    public void setINT5(Integer INT5) {
        this.INT5 = INT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT6
     *
     * @return the value of wfdefine.INT6
     *
     * @mbggenerated
     */
    public Integer getINT6() {
        return INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT6
     *
     * @param INT6 the value for wfdefine.INT6
     *
     * @mbggenerated
     */
    public void setINT6(Integer INT6) {
        this.INT6 = INT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT7
     *
     * @return the value of wfdefine.INT7
     *
     * @mbggenerated
     */
    public Integer getINT7() {
        return INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT7
     *
     * @param INT7 the value for wfdefine.INT7
     *
     * @mbggenerated
     */
    public void setINT7(Integer INT7) {
        this.INT7 = INT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT8
     *
     * @return the value of wfdefine.INT8
     *
     * @mbggenerated
     */
    public Integer getINT8() {
        return INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT8
     *
     * @param INT8 the value for wfdefine.INT8
     *
     * @mbggenerated
     */
    public void setINT8(Integer INT8) {
        this.INT8 = INT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT9
     *
     * @return the value of wfdefine.INT9
     *
     * @mbggenerated
     */
    public Integer getINT9() {
        return INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT9
     *
     * @param INT9 the value for wfdefine.INT9
     *
     * @mbggenerated
     */
    public void setINT9(Integer INT9) {
        this.INT9 = INT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.INT10
     *
     * @return the value of wfdefine.INT10
     *
     * @mbggenerated
     */
    public Integer getINT10() {
        return INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.INT10
     *
     * @param INT10 the value for wfdefine.INT10
     *
     * @mbggenerated
     */
    public void setINT10(Integer INT10) {
        this.INT10 = INT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE1
     *
     * @return the value of wfdefine.DATE1
     *
     * @mbggenerated
     */
    public Date getDATE1() {
        return DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE1
     *
     * @param DATE1 the value for wfdefine.DATE1
     *
     * @mbggenerated
     */
    public void setDATE1(Date DATE1) {
        this.DATE1 = DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE2
     *
     * @return the value of wfdefine.DATE2
     *
     * @mbggenerated
     */
    public Date getDATE2() {
        return DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE2
     *
     * @param DATE2 the value for wfdefine.DATE2
     *
     * @mbggenerated
     */
    public void setDATE2(Date DATE2) {
        this.DATE2 = DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE3
     *
     * @return the value of wfdefine.DATE3
     *
     * @mbggenerated
     */
    public Date getDATE3() {
        return DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE3
     *
     * @param DATE3 the value for wfdefine.DATE3
     *
     * @mbggenerated
     */
    public void setDATE3(Date DATE3) {
        this.DATE3 = DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE4
     *
     * @return the value of wfdefine.DATE4
     *
     * @mbggenerated
     */
    public Date getDATE4() {
        return DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE4
     *
     * @param DATE4 the value for wfdefine.DATE4
     *
     * @mbggenerated
     */
    public void setDATE4(Date DATE4) {
        this.DATE4 = DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE5
     *
     * @return the value of wfdefine.DATE5
     *
     * @mbggenerated
     */
    public Date getDATE5() {
        return DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE5
     *
     * @param DATE5 the value for wfdefine.DATE5
     *
     * @mbggenerated
     */
    public void setDATE5(Date DATE5) {
        this.DATE5 = DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE6
     *
     * @return the value of wfdefine.DATE6
     *
     * @mbggenerated
     */
    public Date getDATE6() {
        return DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE6
     *
     * @param DATE6 the value for wfdefine.DATE6
     *
     * @mbggenerated
     */
    public void setDATE6(Date DATE6) {
        this.DATE6 = DATE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE7
     *
     * @return the value of wfdefine.DATE7
     *
     * @mbggenerated
     */
    public Date getDATE7() {
        return DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE7
     *
     * @param DATE7 the value for wfdefine.DATE7
     *
     * @mbggenerated
     */
    public void setDATE7(Date DATE7) {
        this.DATE7 = DATE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE8
     *
     * @return the value of wfdefine.DATE8
     *
     * @mbggenerated
     */
    public Date getDATE8() {
        return DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE8
     *
     * @param DATE8 the value for wfdefine.DATE8
     *
     * @mbggenerated
     */
    public void setDATE8(Date DATE8) {
        this.DATE8 = DATE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE9
     *
     * @return the value of wfdefine.DATE9
     *
     * @mbggenerated
     */
    public Date getDATE9() {
        return DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE9
     *
     * @param DATE9 the value for wfdefine.DATE9
     *
     * @mbggenerated
     */
    public void setDATE9(Date DATE9) {
        this.DATE9 = DATE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DATE10
     *
     * @return the value of wfdefine.DATE10
     *
     * @mbggenerated
     */
    public Date getDATE10() {
        return DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DATE10
     *
     * @param DATE10 the value for wfdefine.DATE10
     *
     * @mbggenerated
     */
    public void setDATE10(Date DATE10) {
        this.DATE10 = DATE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT1
     *
     * @return the value of wfdefine.FLOAT1
     *
     * @mbggenerated
     */
    public Float getFLOAT1() {
        return FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT1
     *
     * @param FLOAT1 the value for wfdefine.FLOAT1
     *
     * @mbggenerated
     */
    public void setFLOAT1(Float FLOAT1) {
        this.FLOAT1 = FLOAT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT2
     *
     * @return the value of wfdefine.FLOAT2
     *
     * @mbggenerated
     */
    public Float getFLOAT2() {
        return FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT2
     *
     * @param FLOAT2 the value for wfdefine.FLOAT2
     *
     * @mbggenerated
     */
    public void setFLOAT2(Float FLOAT2) {
        this.FLOAT2 = FLOAT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT3
     *
     * @return the value of wfdefine.FLOAT3
     *
     * @mbggenerated
     */
    public Float getFLOAT3() {
        return FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT3
     *
     * @param FLOAT3 the value for wfdefine.FLOAT3
     *
     * @mbggenerated
     */
    public void setFLOAT3(Float FLOAT3) {
        this.FLOAT3 = FLOAT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT4
     *
     * @return the value of wfdefine.FLOAT4
     *
     * @mbggenerated
     */
    public Float getFLOAT4() {
        return FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT4
     *
     * @param FLOAT4 the value for wfdefine.FLOAT4
     *
     * @mbggenerated
     */
    public void setFLOAT4(Float FLOAT4) {
        this.FLOAT4 = FLOAT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT5
     *
     * @return the value of wfdefine.FLOAT5
     *
     * @mbggenerated
     */
    public Float getFLOAT5() {
        return FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT5
     *
     * @param FLOAT5 the value for wfdefine.FLOAT5
     *
     * @mbggenerated
     */
    public void setFLOAT5(Float FLOAT5) {
        this.FLOAT5 = FLOAT5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT6
     *
     * @return the value of wfdefine.FLOAT6
     *
     * @mbggenerated
     */
    public Float getFLOAT6() {
        return FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT6
     *
     * @param FLOAT6 the value for wfdefine.FLOAT6
     *
     * @mbggenerated
     */
    public void setFLOAT6(Float FLOAT6) {
        this.FLOAT6 = FLOAT6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT7
     *
     * @return the value of wfdefine.FLOAT7
     *
     * @mbggenerated
     */
    public Float getFLOAT7() {
        return FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT7
     *
     * @param FLOAT7 the value for wfdefine.FLOAT7
     *
     * @mbggenerated
     */
    public void setFLOAT7(Float FLOAT7) {
        this.FLOAT7 = FLOAT7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT8
     *
     * @return the value of wfdefine.FLOAT8
     *
     * @mbggenerated
     */
    public Float getFLOAT8() {
        return FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT8
     *
     * @param FLOAT8 the value for wfdefine.FLOAT8
     *
     * @mbggenerated
     */
    public void setFLOAT8(Float FLOAT8) {
        this.FLOAT8 = FLOAT8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT9
     *
     * @return the value of wfdefine.FLOAT9
     *
     * @mbggenerated
     */
    public Float getFLOAT9() {
        return FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT9
     *
     * @param FLOAT9 the value for wfdefine.FLOAT9
     *
     * @mbggenerated
     */
    public void setFLOAT9(Float FLOAT9) {
        this.FLOAT9 = FLOAT9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.FLOAT10
     *
     * @return the value of wfdefine.FLOAT10
     *
     * @mbggenerated
     */
    public Float getFLOAT10() {
        return FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.FLOAT10
     *
     * @param FLOAT10 the value for wfdefine.FLOAT10
     *
     * @mbggenerated
     */
    public void setFLOAT10(Float FLOAT10) {
        this.FLOAT10 = FLOAT10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfdefine.DOMAIN_ID
     *
     * @return the value of wfdefine.DOMAIN_ID
     *
     * @mbggenerated
     */
    public Long getDOMAIN_ID() {
        return DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfdefine.DOMAIN_ID
     *
     * @param DOMAIN_ID the value for wfdefine.DOMAIN_ID
     *
     * @mbggenerated
     */
    public void setDOMAIN_ID(Long DOMAIN_ID) {
        this.DOMAIN_ID = DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfdefine
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(ID);
        sb.append(", NAME=").append(NAME);
        sb.append(", VERSION=").append(VERSION);
        sb.append(", CREATED=").append(CREATED);
        sb.append(", TITLE=").append(TITLE);
        sb.append(", MODIFIED=").append(MODIFIED);
        sb.append(", STATUS=").append(STATUS);
        sb.append(", ISLATEST=").append(ISLATEST);
        sb.append(", INT1=").append(INT1);
        sb.append(", INT2=").append(INT2);
        sb.append(", INT3=").append(INT3);
        sb.append(", INT4=").append(INT4);
        sb.append(", INT5=").append(INT5);
        sb.append(", INT6=").append(INT6);
        sb.append(", INT7=").append(INT7);
        sb.append(", INT8=").append(INT8);
        sb.append(", INT9=").append(INT9);
        sb.append(", INT10=").append(INT10);
        sb.append(", DATE1=").append(DATE1);
        sb.append(", DATE2=").append(DATE2);
        sb.append(", DATE3=").append(DATE3);
        sb.append(", DATE4=").append(DATE4);
        sb.append(", DATE5=").append(DATE5);
        sb.append(", DATE6=").append(DATE6);
        sb.append(", DATE7=").append(DATE7);
        sb.append(", DATE8=").append(DATE8);
        sb.append(", DATE9=").append(DATE9);
        sb.append(", DATE10=").append(DATE10);
        sb.append(", FLOAT1=").append(FLOAT1);
        sb.append(", FLOAT2=").append(FLOAT2);
        sb.append(", FLOAT3=").append(FLOAT3);
        sb.append(", FLOAT4=").append(FLOAT4);
        sb.append(", FLOAT5=").append(FLOAT5);
        sb.append(", FLOAT6=").append(FLOAT6);
        sb.append(", FLOAT7=").append(FLOAT7);
        sb.append(", FLOAT8=").append(FLOAT8);
        sb.append(", FLOAT9=").append(FLOAT9);
        sb.append(", FLOAT10=").append(FLOAT10);
        sb.append(", DOMAIN_ID=").append(DOMAIN_ID);
        sb.append("]");
        return sb.toString();
    }
}